alvr-org/ALVR

ALVR/Launcher.Designer.cs
According to netstat (and some other observations) only port 9943 is listened during headset discovery.
=> Improve message about required firewall openings

alvr_server/IDRScheduler.h
Decrease time between IDR frames during packets loss. 
Might be good to make configurable later. 
Related to #30
=> Decrease minimal time between IDR frames

ALVR/App.config, ALVR/Launcher.Designer.cs, ALVR/Launcher.cs, ALVR/Properties/Settings.Designer.cs, ALVR/Properties/Settings.settings, ALVR/ServerConfig.cs, alvr_server/IDRScheduler.cpp, alvr_server/IDRScheduler.h, alvr_server/Settings.cpp, alvr_server/Settings.h
- Ability to decrease minimum IDR frame interval to 5 ms. 
Useful on networks with packet loss. 
Closes #30
- Fix tab indexes and remove unneeded events.
=> Aggressive keyframe resend and small fixes

ALVR/Launcher.Designer.cs
Fix sound device being reset to default device every time ALVR is opened
and closed without opening Sound tab
=> Remove constantly set CheckState attributes

ALVR-common/packet_types.h, ALVR/Launcher.Designer.cs, ALVR/Launcher.cs, ALVR/Properties/Settings.Designer.cs, ALVR/Properties/Settings.settings, ALVR/ServerConfig.cs, alvr_server/OvrController.cpp, alvr_server/OvrController.h, alvr_server/Settings.cpp, alvr_server/Settings.h
https://github.com/JackD83/ALVR/issues/111
Done.
ハンドトラッキングで動かせるようになった。
位置合わせの問題はあるけれども、現状の動きを極力邪魔せずに動かせるようになったのでプルリクエストした。
OtherタブにIndexとOculusの切り替えボタンを付けた。これで切り替えてSteamVRを起動すると動作が確認できると思う。
一度見てみてほしい。
It can be moved by hand tracking.
Although there was a problem with the alignment, I was able to move the current movement as little as possible, so I requested a pull request.
Added Index and Oculus switch button to Other tab. I think that operation can be confirmed when switching and starting SteamVR with this.
Take a look once.
=> Hand tracking

ALVR/App.config, ALVR/Launcher.Designer.cs, ALVR/Launcher.cs, ALVR/Properties/Settings.Designer.cs, ALVR/Properties/Settings.settings, ALVR/ServerConfig.cs, alvr_server/OvrController.cpp, alvr_server/Settings.cpp, alvr_server/Settings.h, alvr_server/Utils.h
* Add "Presets" tab with "Revert settings to default", "Boneworks controllers fix" and "Set default controller offsets;
* Add configurable controller position and rotation offset + "Other" tab UI refactoring.
I lost at least 1h and an half trying to understand why on the numericUpDowns that I added, when positioned in certain places and when I set a negative value, close and reopen ALVR, the value was clamped to zero. Then I restarted Visual Studio and the sucessive builds didn't had this bug anymore. Also sometimes the tabs get shuffled and the merge diff becomes unreadable. TBH we should scrap WinForms and use WPF or UWP but I have no time for this.
@JackD83 For fixes for other games, please tell me what to add, or else merge this and add them yourself.
=> Add Presets tab + Boneworks controllers fix

ALVR/App.config, ALVR/Launcher.Designer.cs, ALVR/Launcher.cs, ALVR/Properties/Settings.Designer.cs, ALVR/Properties/Settings.settings, ALVR/ServerConfig.cs
Closes #102,  ~# 88~
* Add "Headset emulation mode" (Rift S or Vive)
* Add "Fix image warping" option
* Add DCS preset
I spent another fair bit of time trying to understand why the DCS button or "reset settings" button didn't change comboboxes values when they are the first thing to be clicked after opening ALVR. In the end I fixed both by I calling Launcher.Update() first, then setting non comboboxes related settings, then comboboxes related settings, then calling LoadSettings, in this exact order. I don't have an explanation of why this works and why it didn't work before.
@JackD83 Before merging, please test if the image warping fix works for the other affected games, and tell me if they also need Vive emulation.
=> Add DCS fix

alvr_server/OvrController.cpp, alvr_server/OvrController.h, alvr_server/Utils.h
Added hand animation interpolation.
The resulting animations look perfect, simple linear interpolations was the right call.
The animation duration is set to 15 frames ([here](https://github.com/zarik5/ALVR/blob/experimental/alvr_server/OvrController.h#L52)'s the the relative constant). If you want to make it customizable it should be easy enough.
The PR includes also some minor refactoring.
=> Add hand animation interpolation

alvr_server/AudioCapture.cpp, alvr_server/FrameRender.cpp, alvr_server/Logger.cpp, alvr_server/OvrDirectModeComponent.cpp, alvr_server/OvrHMD.cpp, alvr_server/Poller.cpp, alvr_server/UdpSocket.cpp
resolve #171 
When ALVR.exe call driver_alvr_server.dll's GetSoundDevices function, internal LogDriver function failed to execute because format specification syntax of wchar was incorrect.
I fixed format specification of wchar in alvr_server project.
=> fix format specification syntax of wchar.

alvr_server/driver_virtual_display.vcxproj, alvr_server/shader/ColorCorrectionPixelShader.hlsl, alvr_server/shader/FrameRender.fx, alvr_server/shader/color.hlsli
1. fix colorCorrectionPixelShader
2. change color space from Rec.709(Rift S/sRGB) to Rec.2020(Quest)
1.
Inside the colorCorrectionPixelShader, after applying the sharpen filter, gamma correction is performed with the pow function, but the pow function does not support negative values, so there was a problem in the image.
It was solved by inserting the clamp function just before the pow function.
2.
Oculus Quest's color space is Rec.2020.
[Oculus Device Specifications](https://developer.oculus.com/design/oculus-device-specs/)
convert color space from Rec.709(sRGB) to Rec.2020
=> fix colorCorrectionPixelShader's gamma correction and change color space.

README.md
regarding the readme "Laptops with dual GPU have to disable the on-board GPU." in my experience the onboard graphics can't be disabled, because the  graphics ouput of the dedicated GFX needs to be passed through over the onboard GFX. the dedicated GFX needs to be assigned to the 3d application by settings in the related control panel of the GFX
=> Add information in the readme for notebook users with dedicated GPU

Cargo.lock, README.md, alvr/common/Cargo.toml, alvr/common/src/data/mod.rs, alvr/common/src/data/settings.rs, alvr/common/src/logging.rs, alvr/common/src/process.rs, alvr/server_bootstrap/Cargo.toml, alvr/server_driver_ext/src/lib.rs, alvr/server_driver_ext/src/logging_backend.rs, alvr/web_server/src/logging_backend.rs, alvr/web_server/src/main.rs, alvr/web_server/src/tail.rs, alvr/xtask/src/lib.rs
* `/session` request now require the correct use of GET or POST. POST requests now return code 199 if the settings_cache could not be correctly reconstructed using the given session.json, and settings remain unchanged. Both in case of successful or unsuccessful reconstruction, a `session_old.json` file is created containing a backup of session.json (this file is not created in case the received session.json is already valid). Invalid data for fields other than settings_cache is ignored silently.
* `settings.json` does not exist anymore. The Settings structure is derived from session.json when alvr_server_driver_ext requests it.
* driver_log.txt is now created in the TEMP folder.
* Compilation: speed up compilation times and always check for library updates
* Add `/launch_steamvr` request.
=> Basic session extrapolation

alvr_server/VideoEncoderVCE.cpp
According to https://github.com/obsproject/obs-amd-encoder/wiki/Hardware-Support these features are available from VCE 1.0.
This might need verification. I could test for VCE 2.0.
=> Activate Profile High and Level 5.1 for H264

ALVR/ServerConfig.cs
AMD VCE 1 and 2 can only encode up to 1920px wide content. This is 66.6666% scaling on the Quest (2880px wide).
=> Add scaling of 66% for AMD VCE <=2

alvr_server/OvrController.cpp
This makes the controller root position fix for hand tracking take into account the rotation of the hand to apply the correct offset.
I also changed the second position fix to use HSB_Wrist instead of HSB_Root since HSB_Root offset is ignored by the SteamVR Home hand models.
I will also make a PR with the same changes against the web-ui branch.
=> Fix hand offset drift

alvr/client_hmd/app/src/main/cpp/ovr_context.cpp, alvr/client_hmd/app/src/main/cpp/ovr_context.h
A couple of simple changes to fix the issues I described here: https://github.com/JackD83/ALVR/issues/21#issuecomment-660525020
Rendering thread now computes the haptics start time instead of networking so the last received haptics feedback is guaranteed to play.
I also moved the sine function that generates haptics buffer on the quest to [0,+1] from [-1,+1] so it uses the whole sine instead of just half.
=> Fix missing and weak/pulsing haptics

alvr/client/src/connection.rs, alvr/common/src/data/packets.rs, alvr/common/src/data/session.rs, alvr/common/src/data/settings.rs, alvr/common/src/sockets/control_socket.rs, alvr/server/src/connection.rs, alvr/server/src/lib.rs, server_release_template/web_gui/js/app/nls/settings.js
Added settings for running scripts on connect and disconnect (including SteamVR shutdown).
Previously non-graceful closing of TCP control connection was not detected (as no packets were sent/received), an application level sending of keep-alive messages has been implemented (as it uses new _ServerControlPacket_ and _ClientControlPacket_ values it is not compatible with previous client versions). 
Previously `tokio::net::TcpStream` supported enabling OS level TCP keep-alive, but this functionality was removed in https://github.com/tokio-rs/tokio/pull/1767.
=> Add running scripts on connect/disconnect

server_release_template/dashboard/js/app/customSettings.js
Add default text for Headset emulation mode and Controller emulation mode on Revert setting dialog to easy to understand.
=> Add missing default text on Revert setting dialog

Cargo.lock, alvr/common/Cargo.toml, alvr/common/src/data/settings.rs, alvr/common/src/sockets/stream_socket/mod.rs, alvr/common/src/sockets/stream_socket/throttled_udp.rs, alvr/server/src/connection.rs
A throttled transfer is needed to avoid bursts in the (mainly) video stream on networks with lower bandwidth.
In my case, I use a 5Ghz router which only supports up to 100Mbit Ethernet, so these bursts result in dropped packets and overall an unusable stream.
This PR uses the governor Rust library to implement throttling over a naked UDP socket. The receiving code is a modified version of the UdpFramed Stream implementation.
=> Add throttled UDP socket option for stream socket

alvr/client/android/app/build.gradle
I was a little surprised, when I spotted `[unoptimized + debuginfo]` in my test client build, when compiling with `cargo xtask build-client --release`.
Maybe I am missing something here, but it seems to me, that the alvr-client was never build with optimizations enabled.
We are probably leaving some performance on the table here.
A quick smoke test showed no obvious differences in the experience (I did not compare the numbers).
There should be no harm in enabling the flag. This was probably not left out on purpose anyway.
=> Build android apps with optimizations enabled for release configurations

Cargo.lock, alvr/client/Cargo.toml, alvr/client/android/app/build.gradle, alvr/client/src/connection.rs, alvr/client/src/lib.rs, alvr/common/Cargo.toml, alvr/common/src/data/packets.rs, alvr/common/src/data/version.rs, alvr/common/src/sockets/stream_socket/mod.rs, alvr/common/src/sockets/stream_socket/tcp.rs, alvr/common/src/sockets/stream_socket/throttled_udp.rs, alvr/common/src/sockets/stream_socket/udp.rs, alvr/launcher/Cargo.toml, alvr/server/Cargo.toml, alvr/server/src/connection.rs
Fixes #517.
This PR should likely be reviewed on a commit-by-commit bases.
- 7daf5362cf6ccfc5743d998f508b102887bdb9c6: To send a package between listening on the stream_port and waiting for the server connection the  `StreamSocket::connect_to_server` function had to be split in two.
- c4ec024452939fbaed50162fa240bafb10a4e000: Introduces the `ClientControllPacket::StreamReady` packet.
- a01dab72f3f66a4f6dc63c62d7a556e82962b9b5: Adds version checks to send `StreamReady` only on versions 15.1.0 or higher. This commit should be easily revert-able for 16.0.0 and uses the `reserved` fields on the `ClientConfigPacket` and `HeadsetInfoPacket`. The server has this information already very early in the connection process, but passing it through would be very cumbersome. The client has no idea of …
=> Ack the StreamStart package before attempting to connect

alvr/xtask/src/main.rs
@zarik5 I believe the 'alvr_server' executable was removed in ea3ab930e868683153338a85c4cf710a6ab8196f . However, the code that copies this executable into the driver destination directory had not been removed
=> Fix linux build error in alvr server

alvr/client/android/app/src/main/java/com/polygraphene/alvr/OvrActivity.java
I'm not entirely sure why the removed code was there in the first place. Best I can understand it seems to schedule the frame render 5ms before the next vsync.
Removing it seems to clear up some extra time for the video encoder. Whereas I can usually push the encoder to 110% resolution at 90fps I can now go up to 125% without a noticeable artifacting (white lines) in game. And 120fps now goes up to 100% instead of 80%.
I have not noticed any downsides to this change yet and neither have a few people from the discord that tested my custom build.
I tested both a direct Handler.post() and a postDelayed of 1ms. There didn't seem to be much of a difference performance wise so I opted for the latter to waste less CPU cycles.
=> Removed timing checks, render a decoded frame asap

alvr/common/src/commands.rs, alvr/common/src/data/legacy_session.rs, alvr/common/src/data/session.rs
Previously, this folder had to be created by the user. This commit fixes
that by automatically creating the folder in the rusty SessionManager.
This will break if the `Settings.cpp` parser is used first but it seems
to work fine for the time being.
=> session: create `$XDG_CONFIG_HOME/alvr` on linux

.github/workflows/rust.yml, Cargo.lock, alvr/server/Cargo.toml, alvr/server/build.rs, alvr/server/cpp/platform/linux/CEncoder.cpp, alvr/server/cpp/platform/linux/EncodePipeline.cpp, alvr/server/cpp/platform/linux/EncodePipelineSW.cpp, alvr/server/cpp/platform/linux/EncodePipelineVAAPI.cpp, alvr/server/cpp/platform/linux/ffmpeg_helper.cpp, alvr/server/cpp/platform/linux/ffmpeg_helper.h, alvr/server/cpp/platform/linux/generated/avcodec_loader.cpp, alvr/server/cpp/platform/linux/generated/avcodec_loader.h, alvr/server/cpp/platform/linux/generated/avfilter_loader.cpp, alvr/server/cpp/platform/linux/generated/avfilter_loader.h, alvr/server/cpp/platform/linux/generated/avutil_loader.cpp, alvr/server/cpp/platform/linux/generated/avutil_loader.h, alvr/server/cpp/platform/linux/generated/swscale_loader.cpp, alvr/server/cpp/platform/linux/generated/swscale_loader.h, alvr/server/gen_loader.sh, alvr/server/generate_library_loader.py, alvr/xtask/Cargo.toml, alvr/xtask/src/dependencies.rs, alvr/xtask/src/main.rs
ALVR server requires some specific features in libavutil that are not
currently common in usual distributions, mainly vulkan support.
We add a new flag to the build-server xtask: bundle-ffmpeg, this will
download and compile ffmpeg with the required flags.
In server code, a generated wrapper is used to allow loading through
dlopen in case of bundled libraries or standard dynamic linking for the
general case. The link mode is selected at compile time using the
bundled-ffmpeg feature flag.
=> Support bundled ffmpeg libraries in Linux build

Cargo.toml, alvr/launcher/res/vrcompositor_launcher_wrapper.sh, alvr/launcher/src/commands.rs, alvr/vrcompositor-wrapper/Cargo.toml, alvr/vrcompositor-wrapper/src/main.rs, alvr/xtask/src/main.rs
A wrapper is required to inject the ALVR vulkan layer.
For minimal interference, we want the layer to only be present in
vrcompositor process.
We have 2 possible targets: vrcompositor-launcher and vrcompositor, the
first one must have cap_sys_nice=eip, and the second one must retain the
`vrcompositor` name (argv[0]).
Using a shell script is not possible because it can't have the
capability or retain the name when using exec, an ELF is required. It is
better to replace vrcompositor, so there won't be a prompt to fix
capabilities on each run and we can simply rewrite the wrapper on each
execution.
=> rework compositor wrapper mechanism

alvr/client/android/app/src/main/cpp/ovr_context.cpp
Client was crashing on server connection whenever I had a Bluetooth gamepad connected.
Found I could prevent this crash by skipping gamepads in the updateHapticsState enumeration.
=> Skip BT Gampads in updateHapticsState

alvr/client/android/app/src/main/AndroidManifest.xml
Some relatively recent update to Gradle appears to have changed the default value for android:extractNativeLibs to 'false' (where not explicitly specified). This causes the client APK install to fail. This edit sets it to 'true' in the app manifest.
=> Explicitly enable extractNativeLibs

alvr/server/cpp/alvr_server/ChaperoneUpdater.cpp, alvr/server/cpp/alvr_server/ChaperoneUpdater.h, alvr/server/cpp/platform/linux/CEncoder.cpp
On Linux, poses are taken from vrcompositor stack, which are in an
arbitrary coordinate system. This commit tracks the transormation
between raw positions and openvr positions, through chaperone update.
Should fix one source of jitter.
=> Use correct origin for linux pose tracking

alvr/client/android/app/src/main/cpp/latency_collector.cpp, alvr/client/android/app/src/main/cpp/latency_collector.h, alvr/client/android/app/src/main/cpp/ovr_context.cpp
Cherry-picked from #695.
<hr>
Correct timing for tracking prediction of the headset and controllers. Seems to work best with ExtraLatencyMode off. Unstable if latency is too high.
=> Use total latency for tracking prediction

alvr/client/src/connection.rs, alvr/common/src/data/packets.rs, alvr/server/src/connection.rs
Closes #513.
This change removes some of the cruft introduced in the minor releases
since the initial v15 release.
=> v16 protocol updates

alvr/server/cpp/platform/linux/ffmpeg_helper.h
No need to downgrade vulkan-headers on Arch. Everything compiles fine now. 
Newer vulkan-headers added a runtime version check, but ALVR hadn't implemented a version getter method, so the check couldn't be compiled. This PR adds the method that was missing.
Let me know if this code should be moved. Not sure if it's OK to add the implementation in the header file even though it's so simple.
=> Fix #768: Add alvr::VkContext::dispatch::getVkHeaderVersion()

alvr/xtask/src/main.rs, alvr/xtask/src/packaging.rs
This flag allows for downstream packagers to get reproducible builds
working without avoiding the xtask abstraction layer.
=> xtask: add --reproducible flag

alvr/client/android/app/src/main/cpp/latency_collector.cpp, alvr/client/android/app/src/main/cpp/ovr_context.cpp
In some cases high latency causes controller tracking to stop
I don't know if lowering the latency prediction limit is necessary, increasing the tracking frames might be enough
=> Controller tracking fix

alvr/server/cpp/alvr_server/Logger.cpp
```
warning: cpp/alvr_server/Logger.cpp: In function ‘void _log(const char*, __va_list_tag*, void (*)(const char*))’:
warning: cpp/alvr_server/Logger.cpp:12:12: warning: comparison of integer expressions of different signedness: ‘int’ and ‘long unsigned int’ [-Wsign-compare]
warning:    12 |  if (count > sizeof(buf))
warning:       |      ~~~~~~^~~~~~~~~~~~~
```
=> alvr_server/Logger: fix regression in #798

alvr/server/cpp/platform/linux/CEncoder.cpp, alvr/server/cpp/platform/linux/CEncoder.h, alvr/server/cpp/platform/linux/protocol.h, alvr/vulkan-layer/wsi/headless/surface_properties.cpp, alvr/vulkan-layer/wsi/headless/swapchain.cpp, alvr/vulkan-layer/wsi/headless/swapchain.hpp
It appears that the work done to add shared memory for communication between server and client is causing crashes on Linux. More information: https://github.com/alvr-org/ALVR/issues/823
=> Disable Shared Memory Due to Linux Performance Issues

packaging/alvr_build_linux.sh
This adds auto-detection of the script location when it is inside of a repository tree, which fixes issue #917 .
=> Fix for ISSUE-917: Allow Linux Build Script to Run Inside Repository Tree 

.github/workflows/rust.yml, Cargo.lock, alvr/server/cpp/platform/linux/CEncoder.cpp, alvr/server/cpp/platform/linux/EncodePipeline.cpp, alvr/server/cpp/platform/linux/EncodePipelineNvEnc.cpp, alvr/server/cpp/platform/linux/EncodePipelineNvEnc.h, alvr/xtask/Cargo.toml, alvr/xtask/src/dependencies.rs, alvr/xtask/src/main.rs, alvr/xtask/src/packaging.rs, packaging/alvr_build_linux.sh, packaging/deb/cuda.pc, packaging/rpm/alvr.spec, packaging/rpm/cuda.pc
Added NVenc encoder for Linux.
The current solution is to implement a loop to get the Vulkan frame and copy that through the CPU to the GPU again.
Current latency in my case is in the range of 5-10ms for encoding. But that is already playable quality and latency.
I introduce a new flag `--no-nvidia` to build in dev mode for people with Intel/AMD cards, which is not required to install Nvidia libs to their machines. The flag should pass together with `--bundle-ffmpeg` like example `cargo xtask build-server --bundle-ffmpeg --no-nvidia`. But if you will link to the existing FFmpeg on your machine it's don't need to provide at all, it's only like a modification flag for `--bundle-ffmpeg`.
For devs with Arch need to create a symbolic link from `/opt/cuda` to `/usr/local/cuda` because current …
=> Nvidia linux. Add encoder nvenc

packaging/alvr_build_linux.sh
This fixes a bug which occurs when the build script attempts to copy / rename the APKs:
```
> Task :app:compileOculusGoStableReleaseJavaWithJavac
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.5/userguide/command_line_interface.html#sec:command_line_warnings
BUILD SUCCESSFUL in 25s
33 actionable tasks: 32 executed, 1 up-to-date
Done [2m 26s]
cp: cannot stat 'ALVR/packaging/..//build/alvr_client_oculus_go/*': No such file or directory
cp: cannot stat 'ALVR/packaging/..//build/alvr_client_oculus_quest/*': No such file or directory …
```
=> Fixed a bug causing copy failures

packaging/alvr_build_linux.sh, packaging/deb/control
This adds `nvidia-cuda-toolkit` as a build dependency, adds the package config path, and fixes the control file dependency list.
=> Fix Deb Packaged Builds

.github/workflows/prepare-release.yml, alvr/xtask/src/command.rs, alvr/xtask/src/packaging.rs
- Fixes release workflow (broken due to xtask changes)
- Adds .tar.gz support to `package-server` (only creation, and only on linux)
- Merges `build_linux_server` and `build_linux_server_portable` to avoid building twice.
- The portable build should now include all required libraries
=> Linux portable build fix

android/app/src/main/cpp/gl_render_utils/render_pipeline.cpp
When you exit the client, re-open the client connection to the server, and enter the stream connection, it will cause invalid values and crash the client
=> Client reconnection crash

alvr/audio/src/lib.rs
Surprisingly, the main thing breaking audio support on Linux is that sound servers like PulseAudio support arbitrary sample rates (often all the way down to 1 Hz) and ALVR assumes that it can just select the minimum allowed sampling rate for game audio. This breaks pretty badly, especially as the client code is not designed to handle such unreasonable sample rates. This patch uses 48kHz sampling instead if it's supported and arbitrary sampling rates are allowed - this should be a reasonable choice as modern systems tend to use this internally, including Linux, Android, and even recent Windows versions. Otherwise it keeps the previous behaviour. 
With this patch users still need to use an external program like pavucontrol to route ALVR's audio to and from the correct sources, but other …
=> Unbreak Linux audio by selecting 48kHz sampling rate if given choice

alvr/server/cpp/alvr_server/OvrController.cpp
Just send index trackpad touch event if finger on thumb rest zone on quest 2. 
Checked on mine local build, works as intended (look to right controller trackpad)
.
=> Send trackpad touch event from thumb rest

alvr/server/cpp/alvr_server/OvrController.cpp
Just send values to fingers directly from grip and trigger , rather than emulating two states of them. Checked on vrchat and some demos - works perfectly.
=> Make index controller fingers emulation smoother

android/app/src/main/AndroidManifest.xml
By default (on quest for a sample) we have 256M heapsize, but with largeHeap=true, we can utilize all 512M heap limit. Its helps to avoiding OutOfMemory crashes with large stream resolutions.  https://developer.android.com/guide/topics/manifest/application-element#largeHeap
=> Enable largeHeap in manifest

alvr/xtask/src/dependencies.rs
ffmpeg link is dead, this PR bumps the version to 5.1.
From the [ffmpeg releases page](https://github.com/BtbN/FFmpeg-Builds/releases), 5.0 and 5.1 have the same ABI so it should be functionally the same. 
> Bump release from 5.0 to 5.1.
> 5.1 and 5.0 share the same ABI, so instead of cluttering the list even more, just bump to 5.1 entirely.
=> Fix ffmpeg dependency dead link

alvr/server/cpp/alvr_server/Statistics.h
Tested the change on Oculus Quest 2. This resolves the adaptive bitrate getting stuck problem.
=> Fix adaptive bitrate stuck at minimum

alvr/audio/src/lib.rs, alvr/client_core/src/connection.rs, alvr/client_core/src/lib.rs, alvr/server/src/connection.rs, alvr/sockets/src/stream_socket/mod.rs
When the audio output device switched or unplugged on the PC which run the ALVR server,the streaming would be cut off,and then sometimes the alvr in the HMD crashed at the same time. This modify can retry the game_audio_loop in order to avoid this situation.
=> Retry audio loop when the output audio device is unplugged or switched

alvr/server/cpp/alvr_server/OvrController.cpp
Fixes weird finger behaviors in VRChat.
Grip force should not play a big role in games anyways, lets's just turn it 0/1 instead when the grip is pressed 90%-100%. This has been done for finger tracking too anyways.
=> Fix too aggressive grip force

android/app/src/main/cpp/cpp_main.cpp
Fixes #1237
This has been tested on my Quest 1 with success. 
I assume Oculus Go should be ignored, i don't know what the original reason was in ALVR v18 but i think i should keep it in there.
#
https://user-images.githubusercontent.com/22834512/200428322-49e387a8-1736-43e2-a9f5-c1a86d900db2.mp4
=> Fix controller teleporting on standby

alvr/server/cpp/platform/win32/VideoEncoderVCE.cpp, alvr/server/cpp/platform/win32/VideoEncoderVCE.h
- Fixes high CPU usage (regression introduced by https://github.com/alvr-org/ALVR/pull/1220) and slightly reduces CPU usage comparing to older code.
- Moves out video transmission and encoding pipeline to separate threads.
- Remove AUD reliably for all codecs (fixes H.264 stream with 22.3.1 and 22.5.1).
- Use Infinite GOP for H.264 and HEVC encoding.
- Throw error when 10-bit mode selected with H.264.
=> AMF refactor

alvr/vulkan_layer/layer/layer.cpp
Closes #965
It's not guaranteed there will be a "free" queue that we can add like this.
The old code was also wrong as it compared wrong indexes, but it somehow worked. Not on radv, where `queueProperties[0].queueCount = 1`.
=> vulkan_layer: Fix adding queue in create_device

alvr/server/cpp/platform/linux/EncodePipelineNvEnc.cpp, alvr/server/cpp/platform/linux/EncodePipelineVAAPI.cpp
This should decrease the amount of latency spikes you see on linux.
=> Linux encoder gop size increase

alvr/server/cpp/platform/linux/CEncoder.cpp, alvr/server/cpp/platform/linux/Renderer.cpp, alvr/server/cpp/platform/linux/Renderer.h, alvr/server/cpp/platform/linux/ffmpeg_helper.cpp, alvr/server/cpp/platform/linux/ffmpeg_helper.h, alvr/server/cpp/platform/linux/generated/avutil_loader.h, alvr/server/gen_loader.sh
Fixes compatibility with drivers without DRM modifiers support (notably AMD Polaris GPUs).
Closes #1256
=> Use AV_PIX_FMT_DRM_PRIME format with VAAPI

alvr/server/cpp/alvr_server/OvrController.cpp, alvr/server/cpp/alvr_server/OvrHMD.cpp, alvr/server/cpp/alvr_server/OvrViveTrackerProxy.cpp, alvr/server/cpp/alvr_server/TrackedDevice.cpp
Cherry picked this commit from  #1268
> The second commit aims to reduce code bloat with the openvr singletons. Clang isn't allowed to optimize this properly because the invoked function could have side effects.
In release, `OvrController::Activate` went from 18296 to 10424 bytes (-43%)
`OvrController::onPoseUpdate` from 15201 to 9167 bytes (-40%)
=> reuse ovr singleton references

alvr/server/cpp/platform/linux/EncodePipelineVAAPI.cpp
Ideally it should be INT32_MAX, but vaapi doesn't like that.
=> VAAPI: Set gop_size to INT16_MAX

alvr/vrcompositor_wrapper/src/main.rs
For Vulkan loader < 1.3.234 there is a blacklist of layers
to disable.
For Vulkan loader >= 1.3.234 there is a whitelist of layers
to enable.
=> vrcompositor_wrapper: Disable all Vulkan layers

alvr/server/cpp/platform/win32/VideoEncoderVCE.cpp, alvr/server/cpp/platform/win32/VideoEncoderVCE.h, alvr/session/src/settings.rs
1. Remove `High` HEVC tier (introduced in https://github.com/alvr-org/ALVR/pull/1220) as it seems not to work as intended (ignores AUD NAL skip setting in earlier driver versions) and looks like causing crashes.
2. Make `Speed` quality preset the default option. Speed is safe default and let the user decide if Balanced or Quality is better for them.
3. Remove separate receiver thread (added in https://github.com/alvr-org/ALVR/pull/1227).
=> AMF changes

alvr/server/cpp/alvr_server/ChaperoneUpdater.cpp
These headers are not meant to be used together in one
executable, and issues will arise when compiler decides
to not inline some methods.
Workaround by adding namespace around openvr.h include.
Fixes crash on startup in debug build.
=> Workaround symbol clash in openvr.h / openvr_driver.h 

alvr/vulkan_layer/layer/device_api.cpp, alvr/vulkan_layer/layer/device_api.hpp, alvr/vulkan_layer/layer/layer.cpp, alvr/vulkan_layer/wsi/display.cpp, alvr/vulkan_layer/wsi/display.hpp
Throw away the queue hacks and implement it correctly by waiting on conditional variable.
This also fixes validation errors that would complain about using VkFence from multiple threads.
=> vulkan_layer: Rewrite vsync fence to wait on conditional

alvr/server/cpp/alvr_server/Settings.cpp, alvr/server/cpp/alvr_server/Settings.h, alvr/server/cpp/alvr_server/alvr_server.cpp, alvr/server/cpp/alvr_server/bindings.h, alvr/server/cpp/platform/linux/CEncoder.cpp, alvr/server/cpp/platform/linux/CEncoder.h, alvr/server/cpp/platform/linux/Renderer.cpp, alvr/server/cpp/platform/linux/Renderer.h, alvr/server/cpp/platform/win32/CEncoder.cpp, alvr/server/cpp/platform/win32/CEncoder.h, alvr/server/src/connection.rs, alvr/server/src/web_server.rs, alvr/session/src/lib.rs, alvr/session/src/settings.rs, dashboard/js/app/main.js, dashboard/js/app/nls/main.js, dashboard/js/app/templates/main.html
Option to capture input/output frames.
Also added convenience `Wait()` which can be called before ReportPresent so that the Server Compositor time in statistics only include render time.
=> Renderer debug

alvr/server/cpp/platform/linux/FrameRender.cpp, alvr/server/cpp/platform/linux/FrameRender.h
Load shaders from ~/.config/alvr/shaders/{pre,post} directory.
Subdirectory "pre" applied before internal shaders.
Subdirectory "post" applied after internal shaders.
=> FrameRender: Add support for loading custom shaders

alvr/server/cpp/platform/linux/CEncoder.cpp, alvr/server/cpp/platform/linux/ffmpeg_helper.cpp, alvr/server/cpp/platform/linux/ffmpeg_helper.h
If device lookup fails for whatever reason, fallback to first device.
Also remove special case when using AMF as it's no longer needed.
=> Vulkan: Fallback to first device

alvr/server/cpp/platform/linux/CEncoder.cpp, alvr/server/cpp/platform/linux/EncodePipeline.cpp, alvr/server/cpp/platform/linux/EncodePipelineSW.cpp, alvr/server/cpp/platform/linux/EncodePipelineSW.h, alvr/server/cpp/platform/linux/ffmpeg_helper.cpp, alvr/server/cpp/platform/linux/ffmpeg_helper.h
Latency is actually pretty decent and it could be further reduced by doing the rgb -> yuv conversion on GPU.
=> Fix Linux SW encoder for h264

alvr/server/cpp/platform/linux/CEncoder.cpp, alvr/vulkan_layer/wsi/headless/swapchain.cpp
Layer would eventually deadlock on attempting to write to socket if server wasn't able to drain the buffer fast enough for whatever reason (usually encoder failing).
Also set CLOEXEC to sockets.
Closes #1332
This does fix the crash in linked issue, however it doesn't fix the underlying problem (most likely encoder failing).
=> Use non-blocking socket in vulkan layer

alvr/server/cpp/alvr_server/Settings.cpp, alvr/server/cpp/alvr_server/Settings.h, alvr/server/cpp/platform/linux/EncodePipelineAMF.cpp, alvr/server/cpp/platform/linux/EncodePipelineVAAPI.cpp, alvr/server/cpp/platform/win32/VideoEncoderVCE.cpp, alvr/server/src/connection.rs, alvr/session/src/lib.rs, alvr/session/src/settings.rs, dashboard/js/app/nls/settings.js
Enabling this option may hurt the picture quality, so make it an option and disable by default.
Related issue: https://github.com/GPUOpen-LibrariesAndSDKs/AMF/issues/330.
=> Add VBAQ option

alvr/server/cpp/platform/linux/EncodePipeline.cpp, alvr/server/cpp/platform/linux/EncodePipelineVAAPI.cpp, alvr/server/cpp/platform/linux/EncodePipelineVAAPI.h, alvr/server/cpp/platform/linux/ffmpeg_helper.cpp, alvr/server/cpp/platform/linux/ffmpeg_helper.h
On multi-gpu system it may end up using wrong device otherwise.
=> VAAPI: Use same device as Vulkan context

alvr/server/cpp/platform/linux/ffmpeg_helper.cpp
=> Vulkan: Fallback to /dev/dri/renderD128 device path

alvr/server/Cargo.toml, alvr/server/src/connection.rs
Windows sleep may have poor results due to low timer resolution set by default, and even with high resolution timer, the error can still be within +/- 2ms. `spin_sleep` handles timer resolution change before sleep and then does busy-wait for the remaining time to improve accuracy.
Both tests are done at 90hz (target time is 11.11ms).
Time slept with `spin_sleep::sleep()`:
Time slept with `thread::sleep()`:
=> Replace thread sleep with spin_sleep implementation for vsync thread

alvr/server/cpp/platform/linux/EncodePipeline.cpp, alvr/server/cpp/platform/linux/EncodePipelineVAAPI.cpp, alvr/server/cpp/platform/linux/EncodePipelineVAAPI.h, alvr/server/cpp/platform/linux/ffmpeg_helper.cpp, alvr/server/cpp/platform/linux/ffmpeg_helper.h
Vulkan ffmpeg context is not currently needed for AMD GPUs, but it will eventually be required for Vulkan encoder.
This simplifies shared ffmpeg code and moves DRM hw context creation to VAAPI encoder.
=> Always create FFmpeg Vulkan hw context

alvr/server/cpp/alvr_server/alvr_server.cpp, alvr/server/cpp/alvr_server/bindings.h, alvr/server/cpp/platform/linux/CEncoder.cpp, alvr/server/cpp/platform/linux/EncodePipeline.cpp, alvr/server/cpp/platform/linux/EncodePipeline.h, alvr/server/cpp/platform/linux/EncodePipelineSW.cpp, alvr/server/cpp/platform/linux/FormatConverter.cpp, alvr/server/cpp/platform/linux/FormatConverter.h, alvr/server/cpp/platform/linux/Renderer.cpp, alvr/server/cpp/platform/linux/Renderer.h, alvr/server/cpp/platform/linux/ffmpeg_helper.cpp, alvr/server/cpp/platform/win32/OvrDirectModeComponent.cpp, alvr/server/src/lib.rs, alvr/server/src/statistics.rs
It is needed for accurate timings with Vulkan.
=> Statistics: Add offset to ReportPresent/ReportComposed

alvr/audio/src/lib.rs, alvr/client_core/src/audio.rs, alvr/server/src/connection.rs
Extend iterates over the iterable and copies the contents byte by byte which incurs big performance penalty. Just copy slices.
Before:
After:
=> Replace BytesMut extend with extend_from_slice

alvr/audio/src/lib.rs, alvr/client_core/src/audio.rs, alvr/client_core/src/connection.rs, alvr/server/src/connection.rs, alvr/sockets/src/stream_socket/mod.rs
Reduces the necessity in additional copy pass by passing the header and payload directly to StreamReceiver and sends them in separate packets, but removes SenderBuffer API. Improves performance at high load.
Before:
After:
=> Remove SenderBuffer and send data directly

wiki/ALVR-client-and-server-on-separate-networks.md
Added a new section about using [n2n](https://github.com/ntop/n2n) to run ALVR with separated networks.
Was used for integrated with Parsec, but happened to see it also works for ALVR, and switching to UDP + Adaptive bitrate is mostly playable, so I write up the steps to show how to.
=> Wiki: Add section for running with n2n

alvr/server/cpp/platform/win32/VideoEncoderVCE.cpp, alvr/server/cpp/platform/win32/VideoEncoderVCE.h
1. Fix timeout bug when query timeout is not available.
2. Use timeBeginPeriod/timeEndPeriod only when necessary instead of globally (see https://learn.microsoft.com/en-us/windows/win32/api/timeapi/nf-timeapi-timebeginperiod).
=> Minor AMF fixes for Windows

alvr/xtask/src/main.rs
This is to allow for custom patches to work around the ruff areas with ALVR and ffmpeg on Linux.
=> Linux: force bundled ffmpeg

alvr/server/cpp/alvr_server/ClientConnection.cpp, alvr/server/cpp/platform/linux/CEncoder.cpp, alvr/server/cpp/platform/linux/EncodePipeline.cpp, alvr/server/cpp/platform/linux/EncodePipeline.h, alvr/server/cpp/platform/linux/EncodePipelineAMF.cpp, alvr/server/cpp/platform/linux/EncodePipelineAMF.h
Handle NAL filtering globally and remove video buffer copy caused by it from Linux code.
=> Filter NALs globally

alvr/client_core/src/platform/android.rs
1. Avoid additional synchronization and write to image queue directly from callback.
2. Don't skip frame when decoder buffer overflow happens.
3. Use `release_output_buffer_at_time()` to have the same image timestamp as the buffer.
4. Report decoded frame when the image was acquired instead of buffer.
5. Sleep when no output buffer is available yet.
=> Refactor video decoder split

alvr/server/cpp/alvr_server/ClientConnection.cpp
1. Add a check for 3 and 4 byte NAL prefixes.
2. Refactor the functions with pass-by-reference where needed.
=> Fix compatibility with different NAL prefix length

alvr/server/cpp/platform/win32/VideoEncoderSW.cpp, alvr/server/cpp/platform/win32/VideoEncoderSW.h
1. Removes NAL filtering and corresponding buffer copy.
2. Fixes encoding resolution.
3. Disallows usage of H.264 10-bit encoding (x264 produces a proper stream but quest is apparently unable to decode it for some reason).
4. Disallows usage of HEVC (due to some bug with ffmpeg).
5. Fixes VBV buffer size when encoder first created.
6. Removes useless intra-refresh option.
Rock-solid 80fps go brrrr... If we could have a dx11 shader with conversion from rgb to yuv420, that would be great I think.
=> Windows: Refactor software encoding

alvr/server/cpp/platform/win32/VideoEncoderVCE.cpp, alvr/server/cpp/platform/win32/VideoEncoderVCE.h
The main reason to keep it was buggy handling of AUD insertion in H.264 by older AMD drivers (22.3.1 and prior), and for H.265 for very old drivers. But since https://github.com/alvr-org/ALVR/pull/1227, `AMF_VIDEO_ENCODER_INSERT_AUD` and `AMF_VIDEO_ENCODER_HEVC_INSERT_AUD` were enabled for encoder and the issue was gone. I think this code can be safely removed.
=> Windows: Remove SkipAUD from AMF code

alvr/client_core/src/platform/android.rs, alvr/client_openxr/src/lib.rs
1. Use `thread::yield_now()` instead of sleep in render loop. 1ms sleep introduces additional 1ms client compositor latency for little benefit, while with yield we give time to other threads (and we have plenty of threads). Better to be replaced with `Condvar` or MPSC channel.
2. Use `thread::yield_now()` in decoder thread. Same as above, this should help to avoid additional latency and give time for other threads. Unfortunately, there's no other way than poll and we probably want lower latency.
3. Remove "Video frame queue underflow!" when attempting to dequeue a frame and place "Timed out when waiting for frame!" warning when the frame dequeue function timed out. Queue polling triggers this warning lots of times under almost any condition and creates a huge log spam, but we can indicate …
=> Various refactoring

alvr/server/cpp/platform/linux/FormatConverter.h, alvr/server/cpp/platform/linux/Renderer.cpp, alvr/server/cpp/platform/linux/Renderer.h
Make sure things don't crash when Renderer/FrameConverter init fails.
Also check for required extensions.
=> Vulkan: Fix Renderer/FrameConverter destructor crash when init fails

alvr/server/cpp/platform/linux/EncodePipeline.cpp, alvr/server/cpp/platform/linux/EncodePipelineVAAPI.cpp, alvr/server/cpp/platform/linux/ffmpeg_helper.cpp, alvr/server/cpp/platform/linux/ffmpeg_helper.h
Don't try AMF on Intel cards.
Also don't set VAAPI quality as it has different meaning on Intel drivers.
=> Linux Intel encoder fixes

alvr/server/cpp/platform/linux/Renderer.cpp
we were comparing char* pointers and not the actual strings, and so checkExtension always returned false.
=> fix checkExtension always returning false

alvr/client_openxr/src/interaction.rs
these were likely accidentally removed in https://github.com/alvr-org/ALVR/commit/1845b3ba9e22702dd48f6413d5a0fcb47a3e7bf7
=> restore touch actions on A/B/X/Y

alvr/server_data/src/lib.rs, alvr/session/src/lib.rs
This avoids panic (and SteamVR crash as the result) in case `session.json` was somehow corrupted or became invalid due to manual edit.
=> Refactor session.json loading

alvr/server/cpp/platform/linux/CEncoder.cpp, alvr/server/cpp/platform/linux/ffmpeg_helper.cpp, alvr/server/cpp/platform/linux/ffmpeg_helper.h, alvr/server/cpp/platform/linux/protocol.h, alvr/vulkan_layer/layer/private_data.hpp, alvr/vulkan_layer/wsi/headless/swapchain.cpp
Using deviceUUID instead of deviceName to match device will work correctly when multiple GPUs of the same model are present or even across different drivers (eg. happens with AMF).
Keep the first device fallback, but show warning when we hit it.
=> Vulkan: Use deviceUUID to match compositor and server devices

alvr/server/cpp/platform/linux/EncodePipeline.cpp
Instead use fixed 60 fps and calculate target bitrate.
=> EncodePipeline: Don't change framerate

alvr/server/cpp/platform/linux/EncodePipelineAMF.cpp
Also don't try to set MAX_NUM_REFRAMES as it will be rejected anyway.
=> EncodePipelineAMF: Fix setting framerate

alvr/client_core/cpp/bindings.h, alvr/client_core/cpp/graphics.cpp, alvr/client_core/src/opengl.rs, alvr/client_mock/src/main.rs, alvr/server/cpp/alvr_server/bindings.h, alvr/server/src/bitrate.rs, alvr/server/src/connection.rs, alvr/server/src/lib.rs
Fixes struct alignment issue between C++ and Rust on Linux systems
=> replace bools w/ ints in FFI structs

alvr/server/cpp/platform/linux/EncodePipelineSW.cpp, alvr/server/cpp/platform/linux/EncodePipelineVAAPI.cpp, alvr/server/cpp/platform/linux/EncodePipelineVAAPI.h
These encoders just doesn't work with adaptive bitrate. This way they can still be used with constant bitrate.
VAAPI H264 and AMF H264/265 can handle adaptive bitrate/framerate well.
=> Linux: Ignore framerate with x264 and vaapi-hevc encoders

alvr/server/cpp/alvr_server/Logger.cpp
va_list is undefined after passing it to vsnprintf.
=> Logger: Fix calling DriverLog

alvr/vulkan_layer/layer/settings.h
I tried building ALVR on Fedora 38 and it did not work because this header was missing, after adding it works as expected.
=> Include missing header for Fedora 38.

alvr/dashboard/src/dashboard/mod.rs, alvr/server/cpp/platform/win32/FrameRender.cpp, alvr/session/src/settings.rs
This fixes a small typo with various instances of 'StreamVR' instead of 'SteamVR' :)
Most notably, it fixes the dashboard's "SteamVR is restarting" screen
=> Fix 'StreamVR' typo (-> 'SteamVR')

alvr/dashboard/src/dashboard/components/setup_wizard.rs
The back button on the setup wizard was erroneously disabled on the Hardware Requirements page, which is not the first page of the setup wizard.
I assume this is a bug, and the intended behaviour is more likely to be a disabled back button on the first page of the setup wizard.
=> Disable the back button in the setup wizard on the Welcome page

alvr/dashboard/src/dashboard/components/setup_wizard.rs
It seems a little odd that when the setup wizard finishes, there's no 'Finish' button that the user can click. This pull request fixes this by changing the 'Next' button's text to 'Finish' and action to close the setup wizard, only appearing on the last setup page. For consistency, a similar 'Cancel' button is added to the first setup page.
I'm not sure of the code style/requirements for Rust in this project, so please suggest improvements if needed!
Notably, some things to review:
- The code that closes the setup wizard is now a macro (`close_setup_wizard!()`) (I couldn't find a way of doing this with a regular function, suggestions for a more Rust-like pattern are appreciated!)
- Creating the buttons for the setup wizard that operate in a similar fashion (in one state that closes the …
=> Add 'Finish' and 'Cancel' buttons to the setup wizard

alvr/client_core/Cargo.toml, alvr/client_core/build.rs
- Fixes https://github.com/alvr-org/alvr-cardboard/issues/3 
- Static c++stdlib is included already here, no need for linking shared c++stdlib again - https://github.com/alvr-org/ALVR/blob/528fe67df4a8f7ff980da0a8ebe728a627069d29/alvr/client_core/build.rs#L25-L34
=> Remove duplicate c++std library

alvr/dashboard/src/dashboard/mod.rs
Commit 4fa46ce restructured the settings schema, which broke the setup wizard's auto open setting as it was using an old path that had not been updated.
=> Fix setup wizard session settings

Cargo.lock, Cargo.toml, alvr/client_core/src/platform/android.rs, alvr/session/Cargo.toml, alvr/session/src/settings.rs, alvr/xtask/src/build.rs, alvr/xtask/src/dependencies.rs
- low-latency feature crashes on smartphone android, hence made it as a default-enabled feature https://github.com/PhoneVR-Developers/alvr-cardboard/issues/5
- Building for x86 arch enables faster AVD emulation, wider client_core compatibility
- Android enforces only x86 emulator images to run on x86 hosts from API 28 - https://stackoverflow.com/a/74819011
- we can actually stably build for other ABIs as well but waiting for confirmation from https://github.com/googlevr/cardboard/pull/400
- and fixes from upstream module https://github.com/rust-lang/socket2/issues/433
- some useful logging
future todo: build for remaining two ABIs (ref: https://developer.android.com/ndk/guides/abis)
=> fix: alvr_client_core stability issues on smartphone androids

alvr/dashboard/src/steamvr_launcher.rs
I am attempting to create an ALVR Flatpak, and this is the only barrier to a nearly-similar experience as with the AppImage. I don't imagine it impacts many users, since Steam should likely be already registered as the URL handler for `steam://`.
=> Change steam to xdg-open on non-Windows systems

alvr/server/cpp/alvr_server/Controller.cpp, alvr/server/cpp/alvr_server/Controller.h, alvr/server/cpp/alvr_server/alvr_server.cpp, alvr/server/cpp/alvr_server/bindings.h, alvr/server/src/connection.rs, alvr/session/src/settings.rs
This feature lets users switch the power state of ALVR emulated controllers at runtime, without the need for a SteamVR restart.
This is useful to those wishing to use different controllers, for example via OpenVR-SpaceCalibrator.
=> switch for soft-toggling controllers at runtime

alvr/server/cpp/platform/linux/CEncoder.cpp
With CEncoder, the logs tab is pretty much useless because libavcodec spams 3 lines each frame about how the stream params were adjusted.
Let's lower the log level, so that more meaningful messages are easier to spot.
For when there is a need for these messages, a debug build can be used.
This PR was brought to you by the Make Logs Readable Again movement.
=> CEncoder AV log level verbose -> info

Cargo.lock, Cargo.toml
- very quick upstream release: https://github.com/rust-lang/socket2/pull/434 (https://github.com/alvr-org/ALVR/pull/1586)
- seems like there are no CI checks for build-client-lib, tested locally
=> Remove sockets2 patch

alvr/client_core/cpp/graphics.cpp, alvr/client_core/cpp/utils.h
```java
05-11 17:08:26.031  9082  9197 E [ALVR Native]: Linking program failed: Attribute 'vertexNormal' aliases attribute 'vertexTransform' at location 4
05-11 17:08:26.031  9082  9197 E [ALVR Native]:  (cpp/graphics.cpp, 475)
05-11 17:08:26.031  9082  9197 E [ALVR Native]: #ifndef DISABLE_MULTIVIEW
05-11 17:08:26.031  9082  9197 E [ALVR Native]:     #define DISABLE_MULTIVIEW 0
05-11 17:08:26.031  9082  9197 E [ALVR Native]: #endif
05-11 17:08:26.031  9082  9197 E [ALVR Native]: #define NUM_VIEWS 2
05-11 17:08:26.031  9082  9197 E [ALVR Native]: #if defined( GL_OVR_multiview2 ) && ! DISABLE_MULTIVIEW
05-11 17:08:26.031  9082  9197 E [ALVR Native]:     #extension GL_OVR_multiview2 : enable
05-11 17:08:26.031  9082  9197 E [ALVR Native]:     layout(num_views=NUM_VIEWS) in;
05-11 …
```
=> fix: alvr_client_core: Linking program failed: Attribute x aliases attribute y

alvr/client_openxr/src/lib.rs
Pico 4 standard edition still needs this. hangs indefinitely otherwise.
=> revert removal of pico rendering_thread workaround

alvr/server/cpp/platform/win32/OvrDirectModeComponent.cpp
UE5 attempts to create a texture with format `DXGI_FORMAT_R32G8X24_TYPELESS` that cannot be used in combination with `D3D11_BIND_RENDER_TARGET`. Also introduces error handling to avoid problems in the future.
=> Fix UE5 crash with custom depth texture

alvr/session/src/settings.rs
Reason: Setting it to high can cause the encoder to take more than a frame to encode locking SteamVR's render thread
=> Bitrate: Limit silliness 

alvr/filesystem/src/lib.rs
Actual file is libalvr_vulkan_layer.so
(this is trivial, but I was encouraged to do it)
=> Update references to alvr_vulkan_layer.so

alvr/xtask/patches/0001-Add-AV_VAAPI_DRIVER_QUIRK_HEVC_ENCODER_ALIGN_64_16-f.patch, alvr/xtask/patches/0001-vaapi_encode-Enable-global-header.patch, alvr/xtask/patches/0001-vaapi_encode_h265-Set-vui_parameters_present_flag.patch
* enable global header with AMD H264
* fix setting VUI parameters with H265
* fix surface alignment with AMD H265
=> Add more FFmpeg VA-API patches

alvr/dashboard/src/dashboard/components/setup_wizard.rs, alvr/dashboard/src/main.rs
When we change a setting for a reason and users still use the old option because it is not reset because it can be extrapolated which may cause issues rerun the wizard to reset them
=> Run wizard on update to guide users to reset settings

alvr/server/cpp/alvr_server/Settings.cpp, alvr/server/cpp/alvr_server/Settings.h, alvr/server/cpp/platform/linux/EncodePipelineVAAPI.cpp
Change VBV buffer fullness to 100%.
Remove no longer needed HEVC dynamic framerate workaround.
Seems to work now.
=> EncodePipelineVAAPI: Force VBR with adaptive bitrate

alvr/client_core/src/c_api.rs
Headset client crashing on startup https://github.com/alvr-org/ALVR/issues/1610
If I restart my headset, it consistently crashes once, then opens successfully on the second attempt. If i quit the app (and by quit I mean press the oculus button, then press the quit button on the window that pops up), and open it again, it crashes. Open it right after the crash and it works. Quit, open and crash, open no crash, quit, open and crash, open no crash... And so on.
=> Fixed:Headset-client-crashing-on-second-startup

alvr/server/cpp/platform/win32/OvrDirectModeComponent.cpp
Prevents the mutex added in 9d80f78 from getting stuck locked and causing a crash during a subsequent call of `OvrDirectModeComponent::SubmitLayer` by remembering to unlock the mutex in `OvrDirectModeComponent::Present` if it's returning early
=> unlock mutex in OvrDirectModeComponent::Present when returning early

alvr/server/cpp/platform/linux/EncodePipelineVAAPI.cpp
This doesn't really matter all that much since it's only one extra surface, but it would be shame if someone took inspiration here and copied this bad code somewhere else (as I did).
=> EncodePipelineVAAPI: Don't allocate extra VA surface

alvr/client_core/build.rs, alvr/client_core/cpp/gl_render_utils/texture.cpp, alvr/client_core/cpp/graphics.cpp, alvr/client_core/cpp/utils.h
relates to: https://github.com/alvr-org/ALVR/issues/1610, https://github.com/alvr-org/ALVR/pull/1783, completely fixes https://github.com/PhoneVR-Developers/PhoneVR/issues/129
```java
19:55:21.203  I  Successfully compiled shader.
19:55:21.203  I  [ALVR NATIVE] ALVR Poll Event: HUD Message Update - ALVR v21.0.0-dev00
hostname: 3413.client.alvr
IP: 192.168.1.7
Searching for streamer...
Open ALVR on your PC then click "Trust"
next to the client entry
19:55:21.386  D  update hud texture: 
19:55:21.386  E  GL error on cpp\graphics.cpp : 849: GL_INVALID_VALUE
```
Crashes on client on 3rd reopen : o, alvr_client -> Open -OK; close -> reOpen -OK; close -> reOpen !! Crash !!
Online https://github.com/alvr-org/ALVR/blob/6c8c0532ebe1c80b24f49d1146a30929d515a351/alvr/client_core/cpp/graphics.cpp#L838 …
=> fix: OpenGl warmstart crash 🐛

alvr/server/cpp/alvr_server/HMD.cpp, alvr/server/cpp/alvr_server/Settings.cpp, alvr/server/cpp/alvr_server/Settings.h
vulkan setting bit was removed in the latest beta and did affect anything(dead setting), and per other user's reports in the Linux Gaming discord async reprojection is fixed keep it disabled by default or the setting true until testing in ALVR
=> Linux: remove Vulkan async flag change reprojection flag

alvr/server/cpp/platform/linux/EncodePipelineNvEnc.cpp
the name isn't actually descriptive on what it actually does, it actually means how many surfaces to encode at a time
=> Linux: Nvenc set in to encode one surface at a time

README.md, alvr/client_core/cpp/bindings.h, alvr/client_core/cpp/graphics.cpp, alvr/client_core/cpp/srgb_correction_pass.cpp, alvr/client_core/cpp/srgb_correction_pass.h, alvr/client_core/src/c_api.rs, alvr/client_core/src/opengl.rs, alvr/client_openxr/Cargo.toml, alvr/client_openxr/src/interaction.rs, alvr/client_openxr/src/lib.rs, alvr/xtask/src/command.rs, alvr/xtask/src/dependencies.rs
The sRGB correction shader has been disabled as a workaround.
Hand tracking does not work because of an issue with the Lynx native SDK.
=> feat: :sparkles: Add Lynx headset support

.github/workflows/prepare-release.yml
Fixes NVEnc for Linux users, and not just the people using AUR.
=> Update prepare-release.yml to pull nv-codec-headers

alvr/server/src/connection.rs
adds back a `!` that was lost in 096ec85296e4024f8615a16953ba07a785249ba0
=> Fix negated hand tracking skeleton toggle

alvr/xtask/src/dependencies.rs, wiki/Building-From-Source.md
This removes the need for each user to manually download and build nv-codec-headers before building the streamer. I also enabled the `--fatal-warnings` flag because these headers being missing was only considered a warning, which allowed the streamer to be built without Nvidia support even though it was explicitly requested.
=> Download and build nv-codec-headers in prepare-deps

alvr/xtask/flatpak/audio-flatpak-setup.sh, wiki/Flatpak.md
I think it would be helpful to have this on GitHub rather than just on Discord, as it took me a little longer than I liked to piece this together (partly my fault 😅). Wasn't sure where to put the audio setup script, so I put it into the path with the other Flatpak files.
=> docs: add audio setup for Flatpak release

alvr/client_openxr/Cargo.toml
since ultraleap's service uses a TCP loopback socket you need this additional permission. Now hand tracking works!
=> fix(client): lynx r1 hand tracking

alvr/dashboard/src/dashboard/components/connections.rs, alvr/packets/src/lib.rs, alvr/server/src/connection.rs, alvr/server_io/src/lib.rs, alvr/session/src/lib.rs
Appears for each device, and when toggled - automatically adds local ip, disables client discovery and switches to TCP.
When disabled, it removes local ip (though really not that necessary, still did it), enables client discovery, and leaves TCP as is (because alvr doesn't know about previous state, it's safer to just leave it as is).
Supposed to be very easy and useful toggle to not force people to go and learn where those settings are.
In addition, i made label a hyperlink so people can check out what they need to be able to use that toggle.
I think that's my first "real" pr so any comments about how to do things better (especially when writing settings) appreciated.
=> Added basic toggle - cabled mode for devices

wiki/Building-From-Source.md
Updated the instructions to work on Fedora 39 and the latest cuda libs.
I tested this in a small project I made to build ALVR for Fedora 39 in the Gitlab CI/CD system (since the tar.gz didn't work on my env and I wanted to learn how the GitLab CI/CD system worked).
Here is the build output when making this changes: https://gitlab.com/grillo_delmal/alvr_fedora_build/-/pipelines/1061260602
=> Update Fedora instructions on Building-From-Source.md

alvr/server/build.rs
This was throwing up large amounts of warnings that were not suppressed by warning-suppression pragmas intended for MSVC. Since VideoEncoderAMF is only used on win32, filter out AMF cpp files as is done for macos.
=> Don't attempt to build AMF cpp files on linux

alvr/server/src/connection.rs
When initially establishing the connection, if the handshake packet from the client doesn't arrive the client stays registered as connecting and thus retries become impossible. Adb creates a listen socket immediately upon enabling port forwarding. Because the socket gets accepted the server attempts to establish a connection and fails because adb on it's own won't send the handshake packet when the client's not running, thus blocking retries and preventing a connection being made when the client is actually started.
=> Fix initial handshake failure blocking retries

alvr/client_core/src/connection.rs, alvr/client_core/src/decoder.rs, alvr/client_core/src/platform/android/decoder.rs, alvr/common/src/logging.rs, alvr/session/src/settings.rs
*To be clear, this commit was only tested (and I only have the hardware to test it) with PhoneVR.*
That version is https://github.com/20kdc/ALVR/tree/changeling-buffet-pt-2-phonevr-edition .
This code first attempts to use the hardware decoder as usual, and failing that, attempts the software decoder. These software decoder names are "well known" names. As far as I'm aware they're not strictly API-defined, but the alternative is API functions which are *way* too new to be usable to determine software-ness.
Since this functionality only triggers when the previous code would panic, it shouldn't make anything worse.
*To be actually effective, this PR might need constrained baseline encoding. See https://github.com/alvr-org/ALVR/pull/1932*
Possible things of future research:
* "Whatever …
=> Android: When the hardware/default decoder fails to initialize, fall back to software.

alvr/server/cpp/platform/linux/EncodePipelineVAAPI.cpp
As the title suggests, this patch enables 10bit AV1 encoding in VA-API. Thanks to nowrep for explaining how it works. I was looking for a 10bit profile - turns out there isn't one, the encoder just needs a 10bit input.
=> Add support for 10bit AV1 encoding in VA-API

alvr/server/cpp/platform/linux/EncodePipelineVAAPI.cpp
As nowrep pointed out on Discord, the check would always return true as I wrote it, which breaks h264 when 10bit encoding is turned on.
=> Fix boolean always being true

alvr/client_core/src/connection.rs, alvr/client_core/src/sockets.rs, wiki/Use-ALVR-through-a-USB-connection.md
This makes so that if client can't broadcast, it will try to do announce on localhost.
Thus, making wifi requirement being needed on alvr being optional.
I also added and changed some hud signs, as well as removed wiki line about client discovery - apparently if you set ip on server and have adb working, it doesn't matter if you have client discovery enabled or not, it will connect to wired in either case.
=> fix(connection): 🐛 Try localhost if broadcast fails, fixes wifi being required for cabled

wiki/Flatpak.md
The script for setting up audio devices for Flatpak uses the `pw-link` command to connect the microphone's sink to the source. However, this command requires access to the Pipewire socket which is not available in the Steam Flatpak environment by default.
The ff. is the error that occurs when running without the PW socket within the Steam flatpak:
```
~ ❯❯❯ flatpak run --command=sh com.valvesoftware.Steam
[📦 com.valvesoftware.Steam ~]$ pw-link ALVR-MIC-Sink:monitor_FL ALVR-MIC-Source:input_FL
can't connect: Host is down
```
This PR adds a step to add a Flatpak override for the Pipewire socket in order to make the pw-link command work.
It also updates the example path to point to where the previous step asked the user to save the script.
=> Add Pipewire socket permission setup for Flatpak and improve the example path

alvr/server/cpp/alvr_server/Settings.cpp, alvr/server/cpp/alvr_server/Settings.h, alvr/server/cpp/platform/win32/VideoEncoderAMF.cpp, alvr/server/cpp/platform/win32/VideoEncoderAMF.h, alvr/server/cpp/shared/amf/public/common/TraceAdapter.h, alvr/server/src/connection.rs, alvr/session/src/lib.rs, alvr/session/src/settings.rs
It seems to be working nicely from my testing with a Quest 3 and RX 7700XT.
There's a couple of changes to settings, namely:
- Removed "(VAAPI only)" from AV1 codec name.
- Renamed "Enable VBAQ" to "Enable VBAQ/AQ" and added help text explaining that it's AQ on AV1 and VBAQ on the other two.
With this I also updated AMF to v1.4.33, which may bring some improvements elsewhere. (It may be worth looking into the "New AVC / HEVC encoder rate control methods" added in v1.4.28)
=> Support AV1 encoding using AMF on Windows

alvr/server/cpp/platform/linux/EncodePipelineNvEnc.cpp
This looks way too simple to work, but then again, VA-API was basically the same, except it also expected an encoder profile and some other bits and bops for 10bit support, but the Linux NvEnc pipeline never sets a profile for HEVC, either - so I guess it just defaults to the MAIN profile. Somebody should probably test this before it gets merged.
=> Enable NvEnc AV1 encoding on Linux

alvr/server/cpp/alvr_server/FakeViveTracker.cpp, alvr/server/cpp/alvr_server/bindings.h, alvr/server/src/connection.rs, alvr/server/src/tracking.rs, alvr/session/src/settings.rs
adds the ability to disable body trackers without needing to restart steamvr. useful when you want to switch to real trackers, or just be in 3-point tracking for a while.
=> feature: pause body tracking at runtime

alvr/server/cpp/platform/win32/VideoEncoderAMF.cpp, alvr/server/src/connection.rs
Fixes the fact that pre-analysis setting was not obeying the settings in the dashboard.
Also adds warnings about latency in the log.
Finally also prevents any errors due to incompatible settings, prioritising the clashing options over enabling pre-analysis (i.e. don't enable preproc if it isn't, don't disable 10-bit if it's enabled)
=> Fix pre-analysis setting for AMF

alvr/client_core/src/c_api.rs, alvr/client_core/src/connection.rs, alvr/client_core/src/lib.rs, alvr/client_core/src/platform/android/mod.rs, alvr/client_mock/src/main.rs, alvr/client_openxr/src/lib.rs, alvr/packets/src/lib.rs, alvr/server/src/connection.rs, alvr/session/src/settings.rs
Use ugly workaround to inject more info into the VideoStreamingCapabilities packet to not break protocol compatibility. The workaround is kept until v21 is released.
=> feat: :sparkles: Make video capabilities packet extensible; negotiate FFE support

alvr/server/build.rs, alvr/xtask/src/command.rs, alvr/xtask/src/dependencies.rs, alvr/xtask/src/main.rs
In-between did some minor refactor, which probably would need testing on windows just to make sure everything works fine.
Theoretically ffmpeg can use statically linked x264 and be used instead, but it would require refactoring SW encoder to ffmpeg instead, which would be way more work.
Improvement for #1786
For now leaving for review
=> feat: ✨ Make x264 statically linked on Linux

alvr/xtask/src/dependencies.rs
Missed one place where path should have been created.
Caught by client building on nightly failing to unzip to unknown directory.
Related #1987
=> fix(xtask): 🐛 Fix openxr loader build process not creating temp directory

alvr/events/src/lib.rs, alvr/server/cpp/alvr_server/Controller.cpp, alvr/server/cpp/alvr_server/bindings.h, alvr/server/src/tracking.rs
Indices 26-30 are used for the auxiliary bones, and were uninitialized before. This fixes not being able to press the button at the start of The Lab with the Index/robot hands.
Currently I'm not setting the orientation, because I wasn't sure how to accumulate the quaternions.
=> Fix missing aux bones in hand skeleton

alvr/client_core/cpp/srgb_correction_pass.cpp, alvr/server/cpp/alvr_server/Settings.cpp, alvr/server/cpp/alvr_server/Settings.h, alvr/server/cpp/platform/win32/NvEncoder.cpp, alvr/server/cpp/platform/win32/VideoEncoderNVENC.cpp, alvr/server/src/connection.rs, alvr/session/src/lib.rs, alvr/session/src/settings.rs
Very simple, 2 line fix, verified on visionOS client
=> Encode in full range color for NvEncoder on H264/HEVC

alvr/server/cpp/platform/linux/EncodePipelineNvEnc.cpp, alvr/server/cpp/platform/linux/EncodePipelineVAAPI.cpp, alvr/server/cpp/platform/win32/VideoEncoderAMF.cpp
Tested with VAAPI, untested with NvEnc. Windows related changes soon.
=> Encoders: support full 0-255 color range

alvr/server/cpp/alvr_server/ChaperoneUpdater.cpp, alvr/server/cpp/alvr_server/PoseHistory.cpp, alvr/server/cpp/alvr_server/PoseHistory.h, alvr/server/cpp/alvr_server/alvr_server.cpp, alvr/server/cpp/alvr_server/bindings.h, alvr/server/cpp/alvr_server/include/openvr_math.h, alvr/server/src/connection.rs, alvr/server/src/statistics.rs
Closes https://github.com/alvr-org/ALVR/issues/2013
What was changed:
- mat3x3 multiplication in `OnPoseUpdated` was wrong
- replaced with `vrmath::matMul33`
- this alone fixed playspace rotation but only while using standing universe
- do not throw away queued poses when playspace changes
- with the old logic, there would be ~1s drunken period
- transition is smooth after the change
- switch to `VRApplication_Background`
-  this is to get access to `GetTrackingSpace()` which tells us if the universe is seated or standing
- pull seated or standing transform based on current universe
- handle more events that can cause the playspace to shift
- previously, it would only trigger on universe change (standing <> seated)
- `InitOpenvrClient` and `ShutdownOpenvrClient` are now state-aware
- An …
=> fix: linux views when using modified playspace

alvr/client_core/src/audio.rs, alvr/client_core/src/connection.rs
This makes it possible to plug in your headphones without restarting the client(Fixes #1092).
I am still new to rust and not sure if this is best way to solve this but it works for me and it annoyed me a bunch. Open for suggestions!
=> fix(client): reconnect default audio device on disconnect

alvr/audio/src/lib.rs
Adds support for downmixing from 4, 6 and 8 channel audio to both stereo and mono.
**Important note:** This doesn't make Razer's THX Spatial Audio work (their audio device just returns all 0s for the audio samples).
Tested using VB Audio virtual devices.
This is unlikely to have any effect on audio quality (as most apps/games just use stereo anyway), but it will mean people with surround audio configurations won't end up with no audio on the headset side (unless they have a broken virtual surround setup like was mentioned above).
=> Surround audio support

alvr/client_core/src/audio.rs
This is a follow up to my PR #2025, where I encountered an audio crash that happened randomly after a couple of minutes or hours of using it(See https://github.com/alvr-org/ALVR/pull/2025#issuecomment-1995156816).
I reverted the changes and could confirm the commits in the PR being the issue.
Then I looked further and found out that you shouldn't close the audio stream after an error occurred(see commit message) and was testing this fix in this PR for two days now(~6h of continued usage) without a crash. 
I also found out when rebasing, that in a recent commit(https://github.com/alvr-org/ALVR/commit/005c4c7d84cb1d524008b67b8c43a8228b65e8a1#diff-662ca07f68bbbec1317ab607076a66fa0daa81ae07df639d3588832f87c509d6R43) you upgraded the oboe crate to 0.6 even though it had a comment/warning on …
=> fix: oboe crash by not stopping stream on error

alvr/dashboard/src/steamvr_launcher.rs
Switched to using `steam` binary instead of `xdg-open` because it caused issues if you have multiple steams.
Nothing asks which steam to use and alvr launches first one configured *somehow*, and created UB on most systems with multiple steams. I checked using regular `steam` inside flatpak and it seemed to work just fine.
Also made simple check for SteamVR files for situations where someone set proton as compatibility tool (deliberately, or accidentally), or steam did something wrong and assumed windows version of steamvr needed to be installed.
Without that check it just says *some file doesn't exist* without any clues, so i think that's a good change over that.
=> fix(dashboard): 🐛 Use steam uri handler instead of xdg-open and error if linux SteamVR files are missing.

alvr/client_openxr/src/graphics.rs
Apparently Qualcomm's OpenXR runtime doesn't do RGBA16F, so now we have to run through a priority-sorted list of swapchain formats and pick the best one we can get.
=> Fix swapchain unsupported on Lynx R1

alvr/client_core/src/c_api.rs, alvr/server/cpp/alvr_server/ChaperoneUpdater.cpp, alvr/server/cpp/alvr_server/alvr_server.cpp, alvr/server/src/connection.rs
Fixes a segfault in `vrclient.so` originating from `SetChaperoneArea`.
Changes:
- Client: ensure that width and height are finite and not 0
- do not `GetRawZeroPose` from `SetChaperoneArea`. setting the play area will trigger a steamvr event that will cause ALVR to `GetRawZeroPose` in a separate thread. the segfault is likely due to this race condition.
- remove RoomSetupStarting because it's not needed
=> fix: SetChaperoneArea crash

alvr/client_openxr/src/graphics.rs, alvr/client_openxr/src/lobby.rs, alvr/client_openxr/src/stream.rs
Some headsets, including but not limited to the Quest 2 and Quest Pro get a severe performance hit when using float16 swapchain formats.
Let's only allow float16 formats if HDR has been explicitly requested.
=> fix(client_openxr): only use float16 swapchains if HDR is on

.github/workflows/prepare-release.yml
=> fix(ci): 🐛 Enable GPL on linux build and remove AppImage from CI

alvr/dashboard/src/steamvr_launcher.rs
Small fixes, wasn't correctly working for first-time startup (also added logging, verifying just in case)
=> fix(dashboard): 🐛 Check for vrserver instead of vrcompositor, fix first-time startup

alvr/server/cpp/platform/linux/EncodePipelineNvEnc.cpp
Older NVIDIA cards (e.g. GTX 1650) don't support this feature, and
ffmpeg somehow force-enabled it, despite docs saying it should be set to
"auto", and --help saying the default is "disabled". Setting it to
"disabled" in the encoder works around this issue.
ALVR does not currently use multiple B frames, so there should be no
difference and no obvious difference was visible when testing.
The feature is documented as:
"Using B frame as a reference improves subjective and objective encoded
quality with no performance impact. Hence the users enabling multiple B
frames are strongly recommended to enable this feature."
----
Wise man @nowrep said: "just disable it, it's ffmpeg or nvenc bug (it shouldn't explode on this not being supported when b-frames are not used)"
See …
=> set b_ref_mode=0 for ffmpeg NVENC encoder

alvr/xtask/firewall/alvr_fw_config.sh
Figured that it's easy enough to add and will prevent errors in setup for those who doesn't have ufw/firewalld
=> Add firewall rules for iptables on linux

alvr/client_core/src/connection.rs, alvr/dashboard/src/dashboard/components/logs.rs, alvr/dashboard/src/dashboard/components/notifications.rs, alvr/dashboard/src/dashboard/components/settings.rs, alvr/dashboard/src/dashboard/mod.rs, alvr/dashboard/src/main.rs, alvr/dashboard/src/steamvr_launcher.rs, alvr/server/src/connection.rs, alvr/server/src/lib.rs, alvr/server/src/logging_backend.rs, alvr/session/src/settings.rs
I'm unsure if it looks like a hack (the way it works) or a good solution, but i thought it's the best way considering it's coming from schema
=> Bring back UI tabs for settings

.gitignore, alvr/common/src/logging.rs
Problem: when alvr-server panics, it displays a message box with the panic info. But the rfd::MessageDialog replaces the whole message box content with just "An error occuried" which is not really informative. I played around it a little bit and it seems that it does not accept the panic info as the message box content. 
Solution: Shorten the info to display. After that the message box is displayed normally.
=> Fix panic message boxes

alvr/server/cpp/alvr_server/ChaperoneUpdater.cpp, alvr/server/cpp/alvr_server/alvr_server.cpp, alvr/server/cpp/alvr_server/include/openvr_math.h, wiki/Building-From-Source.md
* Fix crash on Linux (by @SniperJoe #2108)
=> Release v20.8.1

.github/ISSUE_TEMPLATE/bug_report.md
"here" is not a name. It does not describe the link. The main reason this is bad is screen readers often list many/most links in a page and usually aren't going to read out the domain or link. Secondly, you have to read the context around the link to understand what is for. Thirdly, it doesn't say what the link is to or where it's from.
=> Clarify link names in template

.gitignore, alvr/client_openxr/Cargo.toml, alvr/client_openxr/src/lib.rs, alvr/xtask/src/build.rs, alvr/xtask/src/dependencies.rs
This PR also removes the permission `WAKE_LOCK`, because AppLab doesn't like it. I forgot why it was there, the app doesn't seem to be affected without it.
The `supportedDevices` doesn't contain "quest3" because that crashes the Quest 1. the Quest 3 support should not actually be affected.
=> chore(client): :rocket: Update manifest for AppLab

alvr/dashboard/src/dashboard/components/statistics.rs, alvr/gui_common/src/theme.rs
~~Colors need to be discussed~~ Resolved. Using Pride colors 🏳️‍🌈
=> feat(dashboard): :lipstick: Tweak graph labels and colors

wiki/Linux-Troubleshooting.md
Or should I also replace all instances of commandline options with "launch options"?
=> docs: Specify location of commandline options

alvr/session/src/settings.rs
Useful on Apple headsets, but maybe it'll be useful on Meta headsets at some point.
=> Increase maximum resolution from 4096 to 8192

alvr/server/src/connection.rs
The streamer refused me to set game audio and microphone to the same device when I was using a custom device.
I can see in the VB cable it may create a loopback problem, where device A's output will be loopback to A's input. But for custom devices, it shouldn't be an issue, as people can route the steam manually within the audio interface.
For example, in my case, Speaker CH 1-2 is my main output that routes to my physical speaker, and Microphone CH 1-2 is my main input, which aggregates streams from both my physical microphone and Virtual Speaker CH 5-6. In this case, I don't see any issue if I set Microphone CH 1-2 as SteamVR's mic which obtains microphone stream via Virtual Speaker CH 5-6.
=> fix: routing assumption basis of microphone loopback detection

alvr/server/cpp/platform/linux/EncodePipelineVAAPI.cpp
Fix for https://github.com/alvr-org/ALVR/issues/2202
After a bit of bisection, I found out that reverting this line fixed the blackscreen issue on my config.
WARN: even though I found that it fixes the issue I do not precisely understand why it does so.
=> fix(server) HEVC black screen on some linux config

alvr/client_openxr/Cargo.toml
Fixes #2244
Fixes a bug where alvr couldn't use 120hz mode on quest 3 due to the system defaulting to reporting max 90hz if the quest 3 isn't listed as a supported device.
=> fix: Add quest3 as supported device in manifest

wiki/Installation-guide.md, wiki/Linux-Troubleshooting.md
=> wiki(linux): Fix Flatpak link; + troubleshooting

alvr/server_io/Cargo.toml, alvr/server_io/src/lib.rs
=> chore: Don't query audio devices on linux

alvr/server_openvr/cpp/platform/win32/OvrDirectModeComponent.cpp
Setting `SharedTextureDesc.SampleDesc.Count` to 0 return an error when using `CreateTexture2D`
Closes #2308
=> Prevent setting SharedTextureDesc to 0 when CreateTexture2D

alvr/client_openxr/src/lib.rs
=> fix(client_openxr): :bug: Fix crash with vibration on Focus 3

alvr/server_openvr/cpp/platform/linux/EncodePipelineNvEnc.cpp
as suggested by @Xaphiosis  on discord
tested using flatpak builder and launcher from other pr - no error popups anymore when using hevc
=> fix for nvenc hevc error popups - issue #2258

alvr/dashboard/src/data_sources.rs, alvr/dashboard/src/main.rs, alvr/dashboard/src/steamvr_launcher/mod.rs, alvr/filesystem/src/lib.rs, alvr/server_core/src/c_api.rs, alvr/server_core/src/connection.rs, alvr/server_core/src/lib.rs, alvr/server_core/src/logging_backend.rs, alvr/server_core/src/web_server.rs, alvr/server_io/src/lib.rs, alvr/server_openvr/src/lib.rs
This PR is required for Monado support, as in that case the FILESYSTEM_LAYOUT should not be initialized using the openvr config.
Furthermore this PR allows ServerCore to be initialized without requiring fs I/O, so it can be easily integrated in unit tests.
=> feat: :sparkles: Allow overwriting fs layout; rename SERVER_DATA_MANAGER to SESSION_MANAGER

alvr/client_core/src/c_api.rs, alvr/client_core/src/connection.rs, alvr/client_core/src/lib.rs, alvr/client_core/src/logging_backend.rs, alvr/common/src/logging.rs, alvr/server_core/src/c_api.rs, alvr/server_core/src/connection.rs, alvr/server_core/src/lib.rs, alvr/server_core/src/logging_backend.rs, alvr/server_openvr/cpp/alvr_server/alvr_server.cpp, alvr/server_openvr/cpp/alvr_server/bindings.h, alvr/server_openvr/src/lib.rs, alvr/session/src/lib.rs, alvr/session/src/settings.rs
Note: I thought about using the tracing crate, but for now there are no strong reasons to do it. Could be slightly cleaner to use attributes for function scopes. In any case the switch can be done at a later moment.
=> feat: :sparkles: Add debug groups

alvr/client_core/src/graphics/staging.rs, alvr/client_core/src/graphics/stream.rs
The main fix is the line `gl.bind_sampler(0, None)`. wgpu binds a sampler object and doesn't unbind it. I also add some more `make_current()` calls for correctness.
=> fix(client_core): :bug: Fix stream on Focus 3 with FFE off

alvr/common/src/logging.rs, alvr/dashboard/src/dashboard/components/logs.rs, alvr/dashboard/src/data_sources.rs, alvr/dashboard/src/logging_backend.rs, alvr/events/src/lib.rs, alvr/server_core/src/c_api.rs, alvr/server_core/src/connection.rs, alvr/server_core/src/logging_backend.rs, alvr/server_core/src/web_server.rs, alvr/server_openvr/build.rs, alvr/server_openvr/cpp/alvr_server/ChaperoneUpdater.cpp, alvr/server_openvr/cpp/alvr_server/Controller.cpp, alvr/server_openvr/cpp/alvr_server/FakeViveTracker.cpp, alvr/server_openvr/cpp/alvr_server/HMD.cpp, alvr/server_openvr/cpp/alvr_server/Logger.cpp, alvr/server_openvr/cpp/alvr_server/PoseHistory.cpp, alvr/server_openvr/cpp/alvr_server/alvr_server.cpp, alvr/server_openvr/cpp/platform/win32/OvrDirectModeComponent.cpp, alvr/server_openvr/cpp/platform/win32/VideoEncoderSW.cpp, alvr/server_openvr/src/lib.rs
This PR achieves multiple things:
* Fix debug group filter not actually filtering logs to file or stdout
* Use log target instead of message prefix to filter debug groups
* Make debug groups separate events
* Make logging to dashboard or file more legible
* Add server impl (SteamVR) group logs
=> fix: :bug: Fix and rework logging

alvr/session/src/settings.rs
`adapt_to_framerate` is used to correct the bitrate calculation when the framerate is lower (or more rarely higher) than expected. In this way, games that run bad can benefit at least from slightly better image quality frame-wise. The problem with this is that it may be sensitive to oscillations in the framerate, and may create an offset between the requested user requested bitrate and the bitrate that is requested to the encoder, even when the framerate normalizes (needs to be investigated).
=> zarik staging

Cargo.toml, alvr/client_core/src/connection.rs, alvr/client_core/src/graphics/lobby.rs, alvr/client_core/src/lib.rs, alvr/client_openxr/src/extra_extensions/body_tracking_fb.rs, alvr/client_openxr/src/extra_extensions/mod.rs, alvr/client_openxr/src/extra_extensions/multimodal_input.rs, alvr/client_openxr/src/interaction.rs, alvr/client_openxr/src/lib.rs, alvr/client_openxr/src/lobby.rs, alvr/client_openxr/src/stream.rs, alvr/common/src/inputs.rs, alvr/common/src/lib.rs, alvr/dashboard/src/dashboard/components/settings_controls/presets/builtin_schema.rs, alvr/packets/src/lib.rs, alvr/server_core/src/connection.rs, alvr/server_core/src/lib.rs, alvr/server_core/src/tracking.rs, alvr/server_openvr/cpp/alvr_server/Controller.cpp, alvr/server_openvr/cpp/alvr_server/Controller.h, alvr/server_openvr/cpp/alvr_server/alvr_server.cpp, alvr/server_openvr/cpp/alvr_server/bindings.h, alvr/server_openvr/src/lib.rs, alvr/server_openvr/src/tracking.rs, alvr/session/src/settings.rs
This PR adds multimodal support on the client and adds a multimodal protocol extension. It's important to understand that multimodal support and multimodal protocol are two distinct orthogonal features.
Multimodal protocol describes how to interpret data sent by the client. without multimodal protocol, controller tracking is described by only `HAND_LEFT`/`HAND_RIGHT` devices in `device_motions`, while hand tracking requires both the hand device motions and the skeletons to be present. With multimodal protocol, only hand skeleton is required for hand tracking.
The old protocol was decided without anticipating a feature like multimodal, so now we have to negotiate multimodal protocol support and switch it on only when both client and server advertise compatibility.
Multimodal support is …
=> Multimodal input

alvr/client_core/src/graphics/stream.rs
=> fix(client_core): :bug: Fix staging texture resolution

alvr/client_openxr/src/extra_extensions/eye_tracking_social.rs, alvr/client_openxr/src/extra_extensions/face_tracking2_fb.rs, alvr/client_openxr/src/extra_extensions/facial_tracking_htc.rs, alvr/client_openxr/src/extra_extensions/multimodal_input.rs
This PR attempts to fix a crash reported when enabling face tracking on the Quest Pro.
This PR fixes undefined behavior using a specific solution. Before we were calling `System<props>::out()` which returns a `MaybeUninit`, and immediately call `assume_uninit()`. Doing so only the corresponding `BaseOutStructure` fields are initialized, that is `ty` and `next`. The other fields are filled with random values. Beside this, calling `assume_uninit()` after attempting to get the properties with `get_system_properties` is not enough. The OpenXR spec doesn't say to return an error if the `next` pointer is populated with an unknown structure. So after the `get_system_properties` call, the `System<props>` struct might still contain random values. Because of this we should ditch the `out()` method …
=> fix(client_openxr): :bug: Fix crash caused by undefined behavior

alvr/client_core/src/c_api.rs, alvr/client_core/src/connection.rs, alvr/client_core/src/lib.rs, alvr/client_mock/src/main.rs, alvr/client_openxr/src/lib.rs, alvr/client_openxr/src/stream.rs, alvr/packets/src/lib.rs, alvr/session/src/settings.rs
The new C API is `alvr_get_server_version` which works similarly to `alvr_get_settings_json`. The value can be obtained only after server connection, and the string length can be obtained by passing a null buffer.
=> feat(client): :sparkles: Expose server version from client_core

alvr/xtask/flatpak/com.valvesoftware.Steam.Utility.alvr.desktop, alvr/xtask/flatpak/com.valvesoftware.Steam.Utility.alvr.json
Flatpak launcher was previously downloading a specific version of binary. Change this so it now does an in-tree build.
TODO: cicd integration (put version number into json?)
=> flatpak launcher now uses latest

alvr/client_core/resources/staging_vertex.glsl, alvr/client_core/resources/stream.wgsl, alvr/client_core/src/graphics/staging.rs, alvr/client_core/src/graphics/stream.rs
This is a workaround for a weird graphics bug. It seems the staging framebuffer cannot write to more than the size of the stream framebuffer, even if they have nothing to do with each other. The fix is to split the staging texture into two so each staging framebuffer has the same size as the stream framebuffers.
This bug has been investigated extensively .This is not a problem with shaders or viewports. The root cause is still unknown.
=> fix(client_core): :bug: Workaround for blank right eye view

alvr/server_openvr/cpp/platform/linux/EncodePipelineSW.cpp, alvr/server_openvr/cpp/platform/linux/EncodePipelineSW.h
This could be related to the issue originally encountered with the idr scheduler improvement (#2403). Idr state wasn't being set by the encode pipeline and was defaulting to `true` according to my testing.
Note that I haven't actually tested this
=> fix(linux): Fix idr reporting from x264

alvr/server_openvr/cpp/alvr_server/Controller.cpp, alvr/server_openvr/cpp/alvr_server/bindings.h, alvr/server_openvr/src/lib.rs
Also refactor some related logic. Tested with every combination of multimodal on/off and hand tracking interaction Disabled/SteamVR 2.0
=> fix(server_openvr): :bug: Fix hand tracking when using Disabled interaction

alvr/server_openvr/cpp/alvr_server/Controller.cpp, alvr/server_openvr/cpp/alvr_server/Controller.h, alvr/server_openvr/cpp/alvr_server/Utils.h, alvr/server_openvr/cpp/alvr_server/alvr_server.cpp
Calculates the hand skeleton velocity based on the controller's last sent `m_pose`; Adds an additional `targetTimestampNs` argument to the controller's `onPoseUpdate`, as well as an additional stored timestamp `m_poseTargetTimestampNs` for that pose to allow calculating the velocity of the controller. This calculation is only performed if `controllerMotion` is missing but the skeleton is present.
Fixes the waving exercise in Aperture Hand Lab, and probably throwing and other interactions in other titles.
=> fix(server_openvr): Calculate velocities for skeleton-based controllers

alvr/dashboard/src/dashboard/components/statistics.rs, alvr/events/src/lib.rs, alvr/gui_common/src/theme.rs, alvr/server_core/src/bitrate.rs, alvr/server_core/src/c_api.rs, alvr/server_core/src/lib.rs, alvr/server_core/src/statistics.rs, alvr/server_openvr/src/lib.rs, alvr/session/src/settings.rs
Now, by the graphs it's clear to see how the requested bitrate and recorded bitrate are roughly the percentage of recorded throughput, given the saturation parameter in Adaptive bitrate. Still, ideally the throughput should be a constant value (on average) independent on the actual selected saturation value. This is not the case and it will get higher or lower depending on the saturation parameter. This is an improvement that can be addressed in the future.
=> refactor(streamer): :recycle: Clarify distinction between bitrate and throughput

alvr/client_core/src/c_api.rs, alvr/client_core/src/connection.rs, alvr/client_core/src/decoder.rs, alvr/client_core/src/lib.rs, alvr/client_core/src/platform/android/decoder.rs, alvr/client_mock/src/main.rs, alvr/client_openxr/src/lib.rs, alvr/client_openxr/src/stream.rs, alvr/session/src/settings.rs
This PR creates a new API for using the decoder. Removed the distinction between internal and external decoder, there is only an "external" implementation. The C API had been tweaked to reflect the internal changes. A significant improvement of this refactor is zero-copy decoder integration for visionOS.
This PR also fixed one bug where the video stream might start in a corrupted state because of a race condition.
=> refactor(client): :recycle: Move decoder out of ClientCoreContext; fix IDR race condition

alvr/client_openxr/src/lib.rs, alvr/client_openxr/src/stream.rs
This PR implement two fixes which independently fix a crash when the stream timestamp is 0. The `xr_frame_stream.end()` retry fallback apparently does not work on the Focus 3, or somehow some internal variables are already changed and we don't need another successful call.
=> fix(client_openxr): :bug: Fix crash on Focus 3 with 0 timestamp

alvr/client_core/src/c_api.rs, alvr/client_core/src/connection.rs, alvr/client_core/src/lib.rs, alvr/client_mock/src/main.rs, alvr/client_openxr/src/lib.rs, alvr/client_openxr/src/stream.rs, alvr/packets/src/lib.rs, alvr/server_core/src/connection.rs, alvr/session/src/settings.rs
I kept seeing people complain about blocking in dark areas on AVP, and the encoding gamma option is a bit hidden :/
Enables client-side preference for 10-bit encoding, full-range encoding, encoding gamma, and HDR. OLED panels benefit from an encoding gamma of 1.5 to prevent the encoder from trying to throw away dark values that aren't visible on LCDs, and this encoding gamma requires 10-bit full-range encoding in order to prevent the color correction from being lossy at 8-bit SDR. 
HDR was also thrown in but I'm not brave enough to make it default on AVP yet, it has a non-zero performance cost that folks in humid clients might actually bump into.
=> feat(dashboard): Client overrides for OLED-pertinent encoding settings (10-bit, encoding gamma, etc)

alvr/xtask/firewall/alvr_fw_config.sh
The /etc/iptables doesn't always exist (like in Pop_OS! for me). Create it if necessary.
=> Create iptables folder during firewall set up if it doesn't exist.

alvr/server_core/src/tracking/mod.rs, alvr/server_core/src/tracking/vmc.rs, alvr/session/src/settings.rs
The [VMC Protocol](https://protocol.vmc.info/english.html) is a protocol to send motion tracking data through OSC for avatar motion applications. It's implemented in software like [VSeeFace](https://www.vseeface.icu/#vmc-protocol-support) and [others](https://protocol.vmc.info/Reference).
Here is a test of it being used through the inochi-session app 
https://github.com/user-attachments/assets/30a7f535-a077-46f8-857e-924c8bf60ed5
=> Publish tracking data through VMC Protocol

alvr/server_openvr/cpp/alvr_server/HMD.cpp, alvr/server_openvr/cpp/platform/win32/CEncoder.cpp, alvr/server_openvr/cpp/platform/win32/CEncoder.h, alvr/server_openvr/cpp/platform/win32/FrameRender.cpp, alvr/server_openvr/cpp/platform/win32/FrameRender.h, alvr/server_openvr/cpp/platform/win32/OvrDirectModeComponent.cpp, alvr/server_openvr/cpp/platform/win32/OvrDirectModeComponent.h
Fixes juddery menus on Riven, and possibly judder on other OpenXR apps (HUDs, 2D menus, text, etc rendered at higher resolutions are the most likely candidates).
[Before](https://youtu.be/cuP-xulPFYY) vs [After](https://youtu.be/ShsK4-j5hZQ)
**tl;dr on compositing**
- To composite with timewarp, we need three things: The exact view poses the layer frame was rendered at, the headset's per-eye view frustum tangents, and a renderer which can render a quad with positions/sizes in meters.
- FrameRender is now passed the pose of each layer, the view tangents, and the eye transforms to make this happen.
- The layer's quad is centered at 0,0 and extended 1 unit out in each direction, and then each direction is multiplied by the view tangents.
- Each layer's quad is projected forward by 700m (to …
=> feat-fix(server_openvr): Add timewarped compositing to Windows OpenVR compositor

Cargo.lock, Cargo.toml, alvr/client_core/Cargo.toml, alvr/client_core/src/c_api.rs, alvr/client_core/src/connection.rs, alvr/client_core/src/lib.rs, alvr/client_core/src/sockets.rs, alvr/client_core/src/video_decoder/android.rs, alvr/client_core/src/video_decoder/mod.rs, alvr/client_openxr/Cargo.toml, alvr/client_openxr/src/interaction.rs, alvr/client_openxr/src/lib.rs, alvr/client_openxr/src/stream.rs, alvr/system_info/Cargo.toml, alvr/system_info/src/android.rs, alvr/system_info/src/lib.rs
=> refactor(client): :recycle: Move platform to alvr_system_info; rename video decoder

Cargo.lock, alvr/client_core/src/c_api.rs, alvr/client_core/src/video_decoder/android.rs, alvr/client_core/src/video_decoder/mod.rs, alvr/client_openxr/src/stream.rs, alvr/server_core/src/connection.rs, alvr/server_openvr/Cargo.toml, alvr/server_openvr/src/lib.rs, alvr/server_openvr/src/props.rs, alvr/session/build.rs, alvr/session/src/settings.rs
We rely on code generation, and we generate a long list of OpenVR props. This list gets copied to the session file even for props we don't use. But even worse, because of how we structured the session generation, the whole list is copied for each added prop (where only one value is used at a time). This PR makes the OpenVR props and Mediacodec props untyped so we work around the issue. Instead I added runtime checks with warns if case of errors.
For OpenVR props, I appended the value type in the prop name as hint for the user.
This PR is not urgent but review when you can
=> feat: :sparkles: Reduce session file length

Cargo.lock, Cargo.toml, alvr/adb/Cargo.toml, alvr/adb/src/connection_state.rs, alvr/adb/src/device.rs, alvr/adb/src/forwarded_port.rs, alvr/adb/src/lib.rs, alvr/adb/src/transport_type.rs, alvr/adb/src/wired_connection.rs, alvr/client_core/src/connection.rs, alvr/dashboard/Cargo.toml, alvr/dashboard/src/dashboard/components/devices.rs, alvr/dashboard/src/dashboard/mod.rs, alvr/events/src/lib.rs, alvr/packets/src/lib.rs, alvr/server_core/Cargo.toml, alvr/server_core/src/connection.rs, alvr/server_io/src/lib.rs, alvr/session/src/lib.rs, alvr/sockets/src/lib.rs
This PR adds a toggle for wired connections in the "Devices" tab. When enabled, ALVR manages the forwarding of the required ports using `adb`. If a system installation of `adb` is present, it will be used, falling back to downloading and installing a local copy otherwise.
Closes #567, closes #2349.
=> feat: integrate adb port forwarding

alvr/server_core/src/lib.rs, alvr/server_openvr/src/lib.rs, alvr/session/src/settings.rs
Add a mandatory 1ms wait for users w/ optimize_game_render_latency off, and otherwise ensure a 10ms dummy wait until a headset connects and we have a statistics context to keep track of the actual vsync interval.
=> fix(server_openvr): Fix CPU/GPU deadlocking at 100% usage before the headset connects

Cargo.lock, alvr/adb/src/commands.rs, alvr/adb/src/lib.rs, alvr/launcher/Cargo.toml, alvr/launcher/src/actions.rs
This PR makes the launcher use the ADB commands from `alvr_adb` and should fix the version downgrade error that could occur when installing the client APK. The download location of the local ADB has been changed to be in the release folder.
=> refactor(launcher): refactor client APK installation from launcher

alvr/client_openxr/src/extra_extensions/multimodal_input.rs, alvr/client_openxr/src/interaction.rs, alvr/client_openxr/src/lib.rs, alvr/client_openxr/src/lobby.rs, alvr/client_openxr/src/stream.rs, alvr/session/src/settings.rs
Avoid the need to restart the OpenXR session. This reduces the chances of connection issues. This PR is needed to move towards Vive eye/face tracking support that was previously disabled.
Combined eye gaze support is removed for Quest and Vive. For Pico, we force enable combined eye gaze.
Now the `InteractionContext` is always initialized with multimodal tracking enabled, and disabled after connection if it's disabled for server.
=> refactor(client_openxr): :recycle: Do not recreate OpenXR session

wiki/Linux-Troubleshooting.md, wiki/Troubleshooting.md
General cleanup and updates,  and making sure users know where wiki for linux issues is.
=> docs(linux): update wiki

wiki/Troubleshooting.md
this is a pull request containing an edit for the Linux troubleshooting wiki docs with info on issue #2537 and how to fix it if encountered
=> docs: temp fix for quest framerate throttling

alvr/client_core/resources/lobby_quad.wgsl, alvr/client_core/resources/stream.wgsl, alvr/client_core/src/c_api.rs, alvr/client_core/src/graphics/lobby.rs, alvr/client_core/src/graphics/mod.rs, alvr/client_core/src/graphics/stream.rs, alvr/client_openxr/src/lobby.rs, alvr/client_openxr/src/stream.rs, alvr/common/src/primitives.rs
~~When reprojection is invoked for Pico headsets, the resolution is noticeably degraded. this is what I expected. But we may have to find another solution.~~
Reduced scope to only provide reprojection support for the C API. Reprojection is always enabled but I believe it's not cause of lower performance, it's a simple vertex transform. Only if the input rotation is not identity, then the image would look blurrier because of aliasing, but otherwise the sampling would be pixel perfect.
=> feat(client): ✨ Add reprojection support for C API

.github/workflows/rust.yml, Cargo.lock, alvr/audio/Cargo.toml, alvr/session/build.rs, alvr/xtask/src/build.rs, alvr/xtask/src/dependencies.rs, wiki/Building-From-Source.md
+ Misc small xtask improvements because people keep breaking the build and not looking where in the code the unwrap is
=> chore(xtask): Dont update run submodule update

wiki/Linux-Troubleshooting.md
Adding PRIME render offload vars to SteamVR alone seems to cause an issue where the SteamVR dashboard will not render.  Running the entire steam client via PRIME render offload fixes it. https://github.com/ValveSoftware/SteamVR-for-Linux/issues/542#issuecomment-1266127370
=> docs(linux): fix for no steamvr dashboard on hybrid graphics

alvr/common/src/primitives.rs, alvr/server_core/src/tracking/mod.rs
The main purpose of this is to reuse this calculation in multiple places in a private fork
=> feat(common): :sparkles: Add `Pose * DeviceMotion` operator

alvr/dashboard/src/main.rs, alvr/launcher/src/main.rs, alvr/xtask/resources/alvr.desktop
It's good practice on Linux and especially Wayland based systems to report a well identifiable appid to the rest of the system. This PR gives the appids `alvr.dashboard` and `alvr.launcher` to the eframe projects respectively.
=> Made the dashboard and launcher report respective appids to the system

alvr/client_core/resources/staging_fragment.glsl, alvr/client_core/resources/stream.wgsl, alvr/client_core/src/graphics/staging.rs, alvr/client_core/src/graphics/stream.rs, alvr/client_openxr/src/stream.rs, alvr/packets/src/lib.rs, alvr/server_core/src/connection.rs
- Fixes full range to be actually negotiated like it should
- Fixes `FIX_LIMITED_RANGE` to be conditional on the negotiated full range
High-level outcomes so far:
- Fixes full range color with HDR enabled/disabled
- Fixes color with limited range and HDR enabled.
=> Full range wgpu partial fix

alvr/server_core/src/connection.rs
This was a hard one. Apparently when using a if-let statement, the compiler will extend the lifetime of every temporary at the right of `=` for the whole if block, not only the matched value. One of the temporaries is the `RwReadLock` from `SESSION_MANAGER.read()`, so even adding a bunch of `.clone()`s wouldn't work. In this case I didn't actually need to use a if-let so i converted it to a plain if statement which doesn't suffer from the same limitations. This weird behavior should be fixed by the 2024 rust edition.
=> fix(server_core): :bug: Fix server locking the session unnecessarily

alvr/client_openxr/src/extra_extensions/eye_gaze_interaction.rs, alvr/client_openxr/src/extra_extensions/mod.rs, alvr/client_openxr/src/interaction.rs, alvr/client_openxr/src/lib.rs
=> fix(client_openxr): :bug: Fix crash on unsupported eye tracking permission on Pico

alvr/server_openvr/src/lib.rs
This is a rather controversial PR. We verified on discord that this is the fix for lower framerate than expected on SteamVR but we don't yet have an explanation of why. The rationale for this change is that SteamVR might get stuck on a low framerate if we initialize on 50ms frametime.
=> fix(server_openvr): :bug: Fix stuck framerate on SteamVR

alvr/server_openvr/src/lib.rs, alvr/session/src/settings.rs
This is exactly the same as the old "Optimize game render latency" but with a different name to make it more clear that you don't want to touch it unless you know what you are doing
=> feat(server_openvr): :sparkles: Add "Enforce server frame pacing"

alvr/dashboard/src/steamvr_launcher/linux_steamvr.rs, wiki/Linux-Troubleshooting.md
Thought that those checks in dashboard are not doing anything good at the moment by printing out only half of the command, so i put vrmonitor fix there, and for all users. Mentioned wiki too.
Added check for amdgpu-pro and amdvlk (since they don't work with steamvr, might as well tell user immediately if it will work)
And updated wiki to make sure all commands have appropriate vrmonitor fix, as many users seem to be confused how to concat them together.
=> feat(linux, steamvr-launcher): Improve logging for gpu checks, add more checks, update wiki

alvr/client_openxr/src/extra_extensions/eye_gaze_interaction.rs, alvr/client_openxr/src/extra_extensions/mod.rs, alvr/client_openxr/src/extra_extensions/multimodal_input.rs, alvr/client_openxr/src/interaction.rs, alvr/client_openxr/src/lib.rs, alvr/client_openxr/src/stream.rs
=> fix(client_openxr): 🐛 Try fixing crash on Quest 2 related to multimodal

alvr/server_core/src/tracking/face.rs
I've noticed that VRCFaceTracking gives lots of `[ALVR Module] Unrecognized prefix:` errors when client is not focused. It should be sending a garbage that is out of vector's "new length".
=> fix: Avoid sending garbage to VRCFT

alvr/client_core/src/lib.rs, alvr/server_core/src/connection.rs, alvr/server_core/src/lib.rs, alvr/server_core/src/tracking/mod.rs
Found the actual fix lol, seems to make hands way less sloshy as well?
=> bugfix(server_core) Fix judder regression caused by streamer-client pose desync

alvr/client_openxr/src/interaction.rs, alvr/common/src/inputs.rs
Pico 4 Ultra has it's own controller profile, so why not add it? It may be the reason of OG issue at https://github.com/alvr-org/ALVR/issues/2586 I guess.
=> feat: Add Pico 4 Ultra controller profile

alvr/client_openxr/src/interaction.rs, alvr/client_openxr/src/lib.rs, alvr/system_info/src/lib.rs
Introduces `Platform::Pico4Enterprise` and `Platform::Pico4Pro`, changes device model detection criteria.
=> feat: Change Pico platform detection

alvr/client_core/src/c_api.rs, alvr/client_openxr/src/extra_extensions/body_tracking_bd.rs, alvr/client_openxr/src/extra_extensions/mod.rs, alvr/client_openxr/src/interaction.rs, alvr/client_openxr/src/lib.rs, alvr/client_openxr/src/lobby.rs, alvr/client_openxr/src/stream.rs, alvr/graphics/src/lobby.rs, alvr/session/src/settings.rs
Resolves https://github.com/alvr-org/ALVR/issues/2072. Tested with two PMT on Pico OS 5.12.0S.
=> feat: Pico Motion Trackers body tracking support

README.md, alvr/client_openxr/src/extra_extensions/passthrough_fb.rs, alvr/client_openxr/src/interaction.rs, alvr/client_openxr/src/lib.rs, alvr/client_openxr/src/passthrough.rs, alvr/common/src/inputs.rs, alvr/system_info/src/lib.rs
- Add PFD MR to platform matcher as a YVR headset
- YVR runtime complains about the passthrough flags needing to be non-zero, [and they're right](https://registry.khronos.org/OpenXR/specs/1.0/man/html/XrCompositionLayerFlagBits.html)
- Fix the color space to be Rec.709, technically it should be Display P3 (P3 with an sRGB white point) or sRGB, but those aren't options and Rec.709 is easy to work with for H26x anyway.
=> feat(client_openxr): Add support for Play for Dream MR + misc fixes for it

alvr/client_openxr/Cargo.toml, alvr/client_openxr/src/extra_extensions/face_tracking2_fb.rs, alvr/client_openxr/src/extra_extensions/facial_tracking_htc.rs, alvr/client_openxr/src/interaction.rs, alvr/client_openxr/src/lib.rs, alvr/client_openxr/src/stream.rs
Tested and working on the Focus Vision. because of a limitation of the runtime, the tracker objects can only be initialized at startup.
=> feat: :sparkles: Add eye and lip tracking on Vive

alvr/server_core/src/connection.rs, alvr/server_core/src/input_mapping.rs, alvr/server_openvr/src/props.rs, alvr/session/src/settings.rs
=> feat: Pico 4 controller emulation

alvr/dashboard/src/dashboard/components/devices.rs, alvr/dashboard/src/steamvr_launcher/mod.rs, alvr/server_io/src/openvrpaths.rs
I'm really not sure what the path is on Windows. I found some references but not a full path, and especially it varies.
This will go into `steamvr.vrsettings` and toggle `blocked_by_safe_mode` if needed for the ALVR driver. Should fail gracefully as long as the file exists.
Windows is not implemented because:
- on Discord the point was raised that Windows SteamVR gets/causes much less trouble with this;
- the path gets more complicated and no source of truth on the web was found that felt safe to quickly implement.
=> feat(steamvr): auto-unblock ALVR driver on startup

alvr/xtask/flatpak/com.valvesoftware.Steam.Utility.alvr.json
It seems rust-stable is limited to rust 1.81 with the 23.08 sdk and that also seems quite old considering a 2 year support window. So we have to update the flatpak sdk.
But I haven't tested this because flatpak is so annoying to get working, we could just send it off to a nightly and see if it works.
=> fix: Update flatpak sdk

alvr/server_openvr/cpp/alvr_server/Controller.cpp, alvr/server_openvr/cpp/alvr_server/HMD.cpp, alvr/server_openvr/cpp/alvr_server/TrackedDevice.cpp, alvr/server_openvr/cpp/alvr_server/TrackedDevice.h, alvr/server_openvr/cpp/alvr_server/alvr_server.cpp, alvr/server_openvr/cpp/alvr_server/bindings.h, alvr/server_openvr/src/lib.rs, alvr/server_openvr/src/props.rs
In this PR I make the following changes:
* Move TrackedDevices initialization and registration from `DriverProvider::Init()` to `InitializeStreaming()`
* Don't wait for the HMD activation to start the alvr_server_openvr event loop
* Because of this, to avoid race conditions, `TrackedDevice::registrer_device()` now waits for the `ITrackedDeviceServerDriver::Activate()` call.
* Don't store tracked devices in `g_driver_provider` until they are successfully activated. This requires changing the signature of `SetOpenvrProps()` and `RegisterButtons()` to reference the devices by pointer instead of ID. Allow controllers and trackers to fail registration (we are already handling the absence of any of these devices)
Notably, In this PR i'm not implementing the skip of the first SteamVR restart …
=> feat(server_openvr): :sparkles: Defer TrackedDevices initialization

Cargo.lock, alvr/dashboard/src/dashboard/components/logs.rs, alvr/dashboard/src/data_sources.rs, alvr/dashboard/src/main.rs, alvr/dashboard/src/steamvr_launcher/linux_steamvr.rs, alvr/dashboard/src/steamvr_launcher/mod.rs, alvr/filesystem/src/lib.rs, alvr/launcher/src/actions.rs, alvr/server_core/src/lib.rs, alvr/server_core/src/web_server.rs, alvr/server_io/src/firewall.rs, alvr/server_openvr/Cargo.toml, alvr/server_openvr/src/lib.rs, alvr/session/src/lib.rs, alvr/session/src/settings.rs, alvr/xtask/src/build.rs, alvr/xtask/src/main.rs
At SteamVR launch, unconditionally register the ALVR driver. Also remove driver list backup.
In this PR I implement some sanity checks, that are now necessary since there is no unregistration of the driver:
* Before launching SteamVR from the dashboard, we unregister any ALVR driver which is not from the current instance
* Bail out at driver entry point (HmdDriverFactory) if we detect a running dashboard not from the same installation
* At dashboard launch, kill every other dashboard instance.
This should be sufficient to handle multiple ALVR installations (Steam release or not).
This PR should be merged only after #2754 and #2757
=> feat: Remove SteamVR driver registration modes

wiki/Linux-Troubleshooting.md
This should hopefully fix issue #2014 for nvidia users. Tested on my system and it works perfectly now after adding `VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/nvidia_icd.x86_64.json`, completely fixing the encoder errors.
=> docs(linux): update wiki to add VK_ICD_FILENAMES fix for nvidia

alvr/client_core/src/connection.rs, alvr/client_openxr/src/graphics.rs, alvr/client_openxr/src/lib.rs, alvr/client_openxr/src/lobby.rs, alvr/client_openxr/src/stream.rs, alvr/packets/src/lib.rs, alvr/server_core/src/connection.rs, alvr/session/src/settings.rs
This is an implementation of Meta’s [composition layer filtering OpenXR extension](https://developers.meta.com/horizon/documentation/native/android/mobile-openxr-composition-layer-filtering/).
It simply consists in detecting said extension, enabling it if available, and adding a set flags on each submitted composition layer to specify the desired level of super sampling and/or sharpening.
I tested it successfully on my Quest 3, and from tests on other OpenXR tools, this should also work at least on Pico headsets.
If the extension is unavailable on the target headset, or if both post-processing settings are left to Disabled in the dashboard, it will fallback to the current existing behavior.
This is my first time working with production-level Rust code, so please correct me on all my …
=> Client-side OpenXR post-processing

alvr/client_openxr/src/interaction.rs
Just adds YVR runtimes to the Hall of Shame, pose prediction feels much better.
=> bugfix: Velocity workaround for PFD MR headset pose

Cargo.lock, alvr/dashboard/Cargo.toml
Possibly fixes #2417 
Could be merged as is, and checked if nightly users have more issues or not (it shouldn't block startup if it fails to work)
=> fix(dashboard): update nvml-wrapper

alvr/xtask/firewall/alvr_fw_config.sh
Fixes #2250
Seems like it was incorrect regex being used, not parsing *all* zones from list of active zones (including public, or any that had other words in line)
=> fix(firewall): linux firewalld zones being parsed incorrectly

alvr/launcher/src/actions.rs, alvr/launcher/src/main.rs, alvr/launcher/src/ui.rs
This feature is Windows-only, because on Linux the session file is written globally on ~/config.
It finds the installations with a session file and shows them in a dropdown when installing a new version. For the edge case where a session file gets deleted during the lifetime of the launcher and the corresponding version is selected, it will gracefully show an error. I don't believe we need to handle this edge case more.
This PR contains also some minor refactoring.
=> feat(launcher): :sparkles: Support copying session file from other installations

alvr/audio/src/lib.rs, alvr/dashboard/src/dashboard/components/logs.rs, alvr/dashboard/src/dashboard/components/settings_controls/presets/builtin_schema.rs, alvr/dashboard/src/dashboard/components/setup_wizard.rs, alvr/server_core/src/connection.rs, alvr/session/src/settings.rs, wiki/Installation-guide.md
Not long ago I thought of completely replacing the microphone support on Windows with just Virtual Audio Cable, as it seems to be actually working, while VB Cable doesn't sometimes (it doesn't work when just installed, it requires a system restart, but better go with the more robust solution).
In this PR I keep VB Cable and VoiceMeeter as second options still. If after user testing VAC results stable and reliable, should I go ahead and make it the only preset option? (I would still allow for custom audio devices by substring)
=> fix: :bug: Make VAC default; soft-fix microphone issues

alvr/adb/src/parse.rs, alvr/audio/src/lib.rs, alvr/audio/src/linux.rs, alvr/client_core/src/c_api.rs, alvr/client_core/src/connection.rs, alvr/client_core/src/video_decoder/android.rs, alvr/client_openxr/src/graphics.rs, alvr/client_openxr/src/interaction.rs, alvr/client_openxr/src/stream.rs, alvr/dashboard/src/dashboard/components/devices.rs, alvr/dashboard/src/dashboard/components/new_version_popup.rs, alvr/dashboard/src/dashboard/components/settings_controls/choice.rs, alvr/dashboard/src/dashboard/components/settings_controls/mod.rs, alvr/dashboard/src/dashboard/components/settings_controls/presets/higher_order_choice.rs, alvr/dashboard/src/dashboard/components/settings_controls/section.rs, alvr/dashboard/src/dashboard/mod.rs, alvr/dashboard/src/data_sources.rs, alvr/dashboard/src/main.rs, alvr/dashboard/src/steamvr_launcher/linux_steamvr.rs, alvr/dashboard/src/steamvr_launcher/mod.rs, alvr/server_core/src/c_api.rs, alvr/server_core/src/connection.rs, alvr/server_core/src/input_mapping.rs, alvr/server_core/src/lib.rs, alvr/server_core/src/tracking/mod.rs, alvr/server_core/src/web_server.rs, alvr/server_io/src/lib.rs, alvr/server_io/src/openvr_drivers.rs, alvr/server_openvr/src/lib.rs, alvr/sockets/src/backend/tcp.rs
This one might need a good eye for review. I slightly messed up when merging if statements, I realized too late that `if a { if b { } } else { }` is not the same as `if a && b { } else { }`. I went through it two times to make sure I haven't left behind bugs. We can merge ` if a { if b { } else {} } else { }` if the else blocks are identical.
I've also converted statements like `if let (Some(a), Some(b)) = (c, d)` to let chains to make them more readable
=> refactor: :recycle: Use let-chains when applicable

alvr/server_openvr/build.rs
Nightly is broken because of a lint on build.rs, somehow that was not hit by CI
=> fix(server_openvr): 🐛 Fix lint on build script

alvr/audio/src/lib.rs, alvr/session/src/settings.rs, wiki/Installation-guide.md
The name of the VAC audio devices were wrong so the VAC microophone option was broken.
This PR would be cherry picked into the v20 branch and released as 20.14.1, together maybe with other bugfixes if needed.
=> fix(audio): :bug: Fix more strings for Virtual Audio Cable

Cargo.lock, Cargo.toml, alvr/client_core/src/c_api.rs, alvr/client_core/src/connection.rs, alvr/client_core/src/lib.rs, alvr/client_mock/src/main.rs, alvr/client_openxr/src/interaction.rs, alvr/client_openxr/src/stream.rs, alvr/common/src/primitives.rs, alvr/packets/src/lib.rs, alvr/server_core/src/c_api.rs, alvr/server_core/src/connection.rs, alvr/server_core/src/lib.rs, alvr/server_core/src/tracking/mod.rs, alvr/server_openvr/cpp/alvr_server/alvr_server.cpp, alvr/server_openvr/cpp/alvr_server/bindings.h, alvr/server_openvr/src/lib.rs, alvr/server_openvr/src/tracking.rs
* Rename most occurrences of `view_params` to `local_view_params`
* Pass global view params with `VideoPacketHeader`
* Add `ext_str` to `VideoPacketHeader` and `Tracking`
This PR should unblock Monado support. There is still some work to do, as currently the Monado port could have some issues with frame timing which results in jittery or untimed head position, which can be felt by strafing for example. Head orientation should work fine. For current SteamVR support I've not seen any issues in my testing.
=> Protocol cleanup (3)

alvr/client_core/cbindgen.toml, alvr/client_core/src/c_api.rs, alvr/client_openxr/src/lobby.rs, alvr/common/src/c_api.rs, alvr/common/src/lib.rs, alvr/graphics/src/lobby.rs, alvr/server_core/cbindgen.toml, alvr/server_core/src/c_api.rs
Just realized that this was possible thanks to some config in cbindgen.toml
=> refactor: :recycle: Move C API primitives to alvr_common

alvr/server_core/src/connection.rs, alvr/server_core/src/tracking/mod.rs
After Protocol cleanup (3), the direction of the view is wrong after recentering or when using room scale guardian. There was a piece of code missing to "unrecenter" the global_view_params that are sent back to the client, which is not aware of the recentering transformations applied on the server side.
Furthermore this PR fixes wrong pivoting when Local position recentering mode is selected. This one I thought I fixed a long while ago but was still unfixed.
=> fix(server_core): :bug: Fix recentering after protocol change

Cargo.lock, Cargo.toml, alvr/client_core/src/c_api.rs, alvr/client_core/src/connection.rs, alvr/client_core/src/lib.rs, alvr/client_core/src/statistics.rs, alvr/client_mock/src/main.rs, alvr/client_openxr/src/lobby.rs, alvr/client_openxr/src/stream.rs, alvr/common/src/primitives.rs, alvr/packets/src/lib.rs, alvr/server_core/src/c_api.rs, alvr/server_core/src/connection.rs, alvr/server_core/src/lib.rs, alvr/server_core/src/tracking/mod.rs, alvr/server_openvr/src/lib.rs
* Move prediction to server side
* Rename `Tracking` to `TrackingData`
* Refactor names of timestamp variables and fields
This PR improves the architecture for potential Monado support, by moving prediction to the server side. Also this PR supersedes https://github.com/alvr-org/ALVR/pull/2481. Video frames must still be pushed with the original tracking poll timestamp, otherwise the code to calculate the total latency breaks. The final step of the tracking rewrite is to remove timestamps as IDs altogether and use pose inter/extrapolation searching to determine their timestamps.
Tested on Quest 3/Windows
This is a breakaway PR from #2901
=> Protocol cleanup (4)

Cargo.lock, Cargo.toml, alvr/client_core/src/c_api.rs, alvr/client_mock/src/main.rs, alvr/client_openxr/src/extra_extensions/body_tracking_bd.rs, alvr/client_openxr/src/interaction.rs, alvr/client_openxr/src/lib.rs, alvr/client_openxr/src/lobby.rs, alvr/client_openxr/src/stream.rs, alvr/common/src/inputs.rs, alvr/common/src/primitives.rs, alvr/graphics/src/lobby.rs, alvr/packets/src/lib.rs, alvr/server_core/src/connection.rs, alvr/server_core/src/tracking/body.rs, alvr/server_core/src/tracking/mod.rs, alvr/session/src/settings.rs
* Use body skeleton inside TrackingData and extract default trackers on the server side
* Send Pico motion trackers as generic trackers and assign default trackers on the server side
This is the last piece from #2901
Tested on Quest 3/Windows
=> Protocol cleanup (6)

alvr/dashboard/src/dashboard/components/settings.rs, alvr/dashboard/src/dashboard/components/settings_controls/presets/builtin_schema.rs, alvr/dashboard/src/dashboard/components/settings_controls/presets/higher_order_choice.rs, alvr/dashboard/src/dashboard/mod.rs, alvr/dashboard/src/data_sources.rs, alvr/events/src/lib.rs, alvr/packets/src/lib.rs, alvr/server_core/src/web_server.rs, alvr/server_io/src/lib.rs, wiki/Installation-guide.md
* Removed output devices selection from preset on Windows
* Removed all the machinery for polling audio devices in the dashboard
* Added notice support for `HigherOrderSettings` and show notice for Headset speaker preset to instruct user how to change default device 
Initially I thought of adding a way to set the system default from the ALVR side. For now I decided for this solution with required user action in case of conflict with mic device, basically keeping it like before. In the future we should automatically change output audio device in case of conflict with microphone. Removing the machinery to poll audio device in the dashboard because it will not be needed even in the future.
This PR must be merged for the v20.14.1 release
=> fix(dashboard): :bug: Remove devices from Headset speaker dropdown

.github/workflows/prepare-release.yml, .github/workflows/rust.yml
The runner windows-2019 was removed some time ago.
This also removes the LIBCLANG env var, the workaround has proven to be fixed from at least the runner windows-2022
=> fix(ci): :green_heart: Fix CI release workflow

Cargo.lock, Cargo.toml, alvr/client_core/src/c_api.rs, alvr/client_core/src/connection.rs, alvr/client_core/src/lib.rs, alvr/client_openxr/src/interaction.rs, alvr/client_openxr/src/stream.rs, alvr/packets/src/lib.rs, alvr/server_core/src/connection.rs
* Merge "active_interaction_profile" and "custom_interaction_profile"
* Add `RealTimeConfig` variant
* Don't send RealTimeConfig if not changed (Note: packets are sent with reliable ControlSocket)
* Explicit all matched packet variants even if unused
Tested
=> Protocol cleanup (7): Reserved to normal packet variants

alvr/dashboard/src/data_sources.rs
On Linux, or when transferring over the session from an older ALVR version, the version popup appears after upgrading even when already on the latest version. In this PR i make sure to reset the checked version to the current version if it's the first time opening the dashboard.
=> fix(dashboard): :bug: Fix unexpected version popup

Cargo.lock, Cargo.toml, alvr/dashboard/Cargo.toml, alvr/packets/Cargo.toml, alvr/server_core/Cargo.toml, alvr/sockets/Cargo.toml, alvr/sockets/src/control_socket.rs, alvr/sockets/src/stream_socket.rs
* Upgrade to to Bincode 2
* Make prefix data little-endian
* Make packet length contain itself (add 4 bytes to the count)
* Remove extra 4 bytes from the max shard length
* Improve performance of send functions (control socket and stream socket) by avoiding double serialization at steady state
* Do not store separately the buffer size where applicable
Initially I wanted to use the new Bincode `Encode` and `Decode` traits in place of serde, given that they seem largely preferred by bincode. This is too cumbersome since we use glam in protocol packets which only implement serde `Serialize` and `Deserialize`. I know that `Decode` is more powerful than `Deserialize` because it allows for custom allocators, but apart from that I'm still unsure if there is any other change we could benefit …
=> Protocol cleanup (8): binary protocol refactoring

alvr/dashboard/src/dashboard/components/settings_controls/presets/builtin_schema.rs
Self-explanatory, just wanted to adjust it so users won't be confused
=> fix (dashboard): Fix incorrect AV1 gpu in note #2331, add more information about headsets

.github/workflows/queue.yml, .github/workflows/rust.yml
Afaik this will need to be merged first before the checks will ever run in the merge queue and after that I'll force the merge queue to be enabled on master so they're actually ran
=> ci: make rarely triggering checks run on merge queue only

.github/workflows/queue.yml
This should actually fix the checks running on merge-queues. After this is merged I can finally set those jobs as required in the github ui so that they actually run on the merge-queue.
=> ci: fix merge-queue actions

Cargo.lock, alvr/dashboard/Cargo.toml, alvr/graphics/Cargo.toml, alvr/graphics/resources/stream.wgsl, alvr/graphics/src/lib.rs, alvr/graphics/src/stream.rs
Tested and working on Quest3/Windows
Apparently wgpu v26 has broken pipeline overrides support
The other dependencies will be updated in another PR
=> refactor(graphics): :arrow_up: Update wgpu to v25

alvr/client_core/Cargo.toml, alvr/client_core/src/audio.rs, alvr/client_openxr/Cargo.toml, alvr/system_info/Cargo.toml, alvr/xtask/src/build.rs
Fixes microphone audio quality regression since https://github.com/alvr-org/ALVR/pull/2860 due to missing input preset setting.
Requires bumping minimum Android API level from 26 to 28.
Tests with default `VoiceRecognition` (1) and `VoiceCommunication` (2) presets on Pico 4 Pro:
=> fix(client_core): Set microphone input preset

alvr/server_core/src/connection.rs, alvr/server_core/src/input_mapping.rs, alvr/server_openvr/src/props.rs, alvr/session/src/settings.rs
Added options for Quest 1 headset emulation and Quest 1 Touch controller emulation, referencing a SteamVR report from the Windows Meta driver, and existing code in the project. I'm sure impact is minimal (especially with the controllers, but SteamVR does load different rendermodels for them), but it's a gap in options that has always bothered me.
Have never programmed with Rust, worked with SteamVR, or contributed to a public project before. Please tell me if I messed up with anything, or if this addition doesn't fit the goals of the project!
=> Add Quest 1 emulation options

alvr/xtask/firewall/alvr_fw_config.sh
ignores (default) after the default zone
fixes #3021
=> fix: correctly parse active zones
