ALVR-common/packet_types.h, ALVR/App.config, ALVR/Launcher.Designer.cs, ALVR/Launcher.cs, ALVR/Properties/Settings.Designer.cs, ALVR/Properties/Settings.settings, ALVR/ServerConfig.cs, alvr_server/ClientConnection.cpp, alvr_server/FFR.cpp, alvr_server/Settings.cpp, alvr_server/Settings.h
Enable setting a vertical offset for the focus center in both FFR implementations.
=> FFR vertical offset

ALVR/App.config, ALVR/Launcher.Designer.cs, ALVR/Properties/Settings.Designer.cs, ALVR/Properties/Settings.settings, ALVR/ServerConfig.cs, alvr_server/OvrHMD.cpp, alvr_server/Settings.cpp, alvr_server/Settings.h
#180 #21
As usual, this is not a real fix but a way to manually adjust the controller haptics intensity.
=> Haptics intensity control

ALVR/App.config, ALVR/Properties/Settings.Designer.cs, alvr_server/shader/FrameRender.fx
- sRGB to REC2020 color conversion removed
- gamma correction 1.12 set as default.
=> Change to a color design that emphasizes appearance

alvr/server_driver/cpp/alvr_server/OvrController.cpp
Same as #217 but against the web-ui branch.
=> Fix hand offset drift (web-ui)

Cargo.lock, server_release_template/web_gui/js/app/setupWizard.js
=> GPU-check Fix

Cargo.lock, server_release_template/web_gui/css/darkly/selectal.min.css, server_release_template/web_gui/css/darkly/style.css, server_release_template/web_gui/css/style.css, server_release_template/web_gui/js/app/customSettings.js, server_release_template/web_gui/js/app/nls/wizard.js, server_release_template/web_gui/js/app/settings.js, server_release_template/web_gui/js/app/setupWizard.js, server_release_template/web_gui/js/app/templates/wizard.html, server_release_template/web_gui/js/lib/selectal.min.css
Also fixed some formatting issues like text being green on hover.
=> Radio button formatting! Radio buttons now look like not radio buttons.

Cargo.lock, alvr/client/Cargo.toml, alvr/client/android/ALVR-common/packet_types.h, alvr/client/android/app/build.gradle, alvr/client/android/app/src/main/cpp/ServerConnectionNative.cpp, alvr/client/android/app/src/main/cpp/bindings.h, alvr/client/src/connection.rs, alvr/client/src/lib.rs, alvr/common/src/logging.rs, alvr/common/src/sockets/mod.rs, alvr/launcher/Cargo.toml, alvr/server/Cargo.toml, alvr/server/cpp/alvr_server/ClientConnection.cpp, alvr/server/cpp/alvr_server/ClientConnection.h, alvr/server/cpp/alvr_server/OvrHMD.cpp, alvr/server/cpp/alvr_server/OvrHMD.h, alvr/server/src/connection.rs, alvr/server/src/lib.rs
The connection system has been replaced with a new one based on TCP. The connection-ful nature of TCP will improve connection reliability. This only works as a control socket; the video, audio, tracking, etc. streams are still managed by the legacy UDP based system.
=> ALVR v14 working prototype

alvr/common/src/data/session.rs, server_release_template/web_gui/js/app.js, server_release_template/web_gui/js/app/main.js, server_release_template/web_gui/js/app/nls/main.js, server_release_template/web_gui/js/app/templates/main.html
=> Add language selection

server_release_template/web_gui/js/app.js, server_release_template/web_gui/js/app/main.js
Sometime the session wasn't updated.
Calling updateSession resolve the problem.
=> Language change bugfix

alvr/common/src/data/session.rs, server_release_template/web_gui/css/darkly/style.css, server_release_template/web_gui/css/style.css, server_release_template/web_gui/js/app/main.js, server_release_template/web_gui/js/app/monitor.js, server_release_template/web_gui/js/app/nls/main.js, server_release_template/web_gui/js/app/nls/monitor.js, server_release_template/web_gui/js/app/templates/main.html, server_release_template/web_gui/js/app/templates/monitor.css, server_release_template/web_gui/js/app/templates/monitor.html
By default the system language is used.
The language can also be reverted to the system language by using the System option.
Some design update (same style of the tabs)
=> Language system update + design update

server_release_template/web_gui/js/app/monitor.js, server_release_template/web_gui/js/app/nls/monitor.js, server_release_template/web_gui/js/app/settings.js, server_release_template/web_gui/js/app/templates/monitor.css, server_release_template/web_gui/js/app/templates/monitor.html
Separate Statistic tab from the Connection tab.
Automatically change the Monitoring page to the Statistic tab on connection and to the Connection tab on disconnection.
+ bugfix on the graph tab
=> Statistic update

server_release_template/web_gui/css/darkly/style.css, server_release_template/web_gui/css/style.css, server_release_template/web_gui/js/app/templates/driver.css, server_release_template/web_gui/js/app/templates/monitor.css, server_release_template/web_gui/js/app/templates/wizard.css
this PR fixes the css trouble we had with the card in statistic and connection.
=> css fixes for connection and statistic

Cargo.lock, alvr/server/cpp/alvr_server/OvrController.cpp, server_release_template/web_gui/js/app/customSettings.js, server_release_template/web_gui/js/app/resources/Quest2.json, server_release_template/web_gui/js/app/resources/Quest2Touch.json
New emulation modes for the HMD and controllers to show up as a Quest 2 in OpenVR.
I didn't make these the default yet but after some more testing maybe we should?
=> Added emulation modes for Quest 2

alvr/common/src/data/settings.rs, server_release_template/web_gui/css/darkly/style.css, server_release_template/web_gui/css/style.css, server_release_template/web_gui/js/app/nls/bg/wizard.js, server_release_template/web_gui/js/app/nls/de/wizard.js, server_release_template/web_gui/js/app/nls/es/wizard.js, server_release_template/web_gui/js/app/nls/fr/wizard.js, server_release_template/web_gui/js/app/nls/it/wizard.js, server_release_template/web_gui/js/app/nls/ja/wizard.js, server_release_template/web_gui/js/app/nls/ru/wizard.js, server_release_template/web_gui/js/app/nls/wizard.js, server_release_template/web_gui/js/app/nls/zh/wizard.js, server_release_template/web_gui/js/app/setupWizard.js, server_release_template/web_gui/js/app/templates/main.html, server_release_template/web_gui/js/app/templates/wizard.html
Add a back button for the wizard.
Fix the menu language selection in vertical mode
Fix the default tracking from 0. (Undefined) to 0.01 (normal)
=> Fixes and improvement

server_release_template/web_gui/index.html, server_release_template/web_gui/js/app/main.js
Just a progress bar to give you company while waiting for the updater to download the update.
=> Progress bar

.gitattributes, .gitignore, server_release_template/web_gui/js/app.js, server_release_template/web_gui/js/app/customSettings.js, server_release_template/web_gui/js/app/driverList.js, server_release_template/web_gui/js/app/languageList.js, server_release_template/web_gui/js/app/languageSelector.js, server_release_template/web_gui/js/app/main.js, server_release_template/web_gui/js/app/monitor.js, server_release_template/web_gui/js/app/settings.js, server_release_template/web_gui/js/app/setupWizard.js, server_release_template/web_gui/js/app/uploadPreset.js
variable are not declared by "var" anymore but by "const" (if never reused) or "let" (if reused).
this also solve some nasty bug or bug wannabe.
=> js code review

alvr/legacy_dashboard/js/app/nls/ko/main.js, alvr/legacy_dashboard/js/app/nls/ko/monitor.js, alvr/legacy_dashboard/js/app/nls/ko/settings.js, alvr/legacy_dashboard/js/app/nls/ko/wizard.js
update legacy_dashboard korean translation
=> update legacy_dashboard korean translation

alvr/legacy_dashboard/js/app/templates/monitor.html
Total Sent statistic is being counted in megabytes not megabits, label should reflect that.
=> Change Mb to MB for Total Sent

alvr/server/build.rs, alvr/server/cpp/alvr_server/IDRScheduler.h, alvr/server/cpp/alvr_server/OvrDisplayComponent.cpp, alvr/server/cpp/alvr_server/OvrHMD.cpp, alvr/server/cpp/alvr_server/OvrHMD.h, alvr/server/cpp/platform/win32/CEncoder.h, alvr/server/cpp/platform/win32/FFR.cpp, alvr/server/cpp/platform/win32/FrameRender.cpp, alvr/server/cpp/platform/win32/FrameRender.h, alvr/server/cpp/platform/win32/NvCodecUtils.h, alvr/server/cpp/platform/win32/NvEncoder.h, alvr/server/cpp/platform/win32/OvrDirectModeComponent.cpp, alvr/server/cpp/platform/win32/OvrDirectModeComponent.h, alvr/server/cpp/platform/win32/VideoEncoder.h, alvr/server/cpp/platform/win32/VideoEncoderNVENC.cpp, alvr/server/cpp/platform/win32/VideoEncoderNVENC.h, alvr/server/cpp/platform/win32/VideoEncoderVCE.cpp, alvr/server/cpp/platform/win32/d3d-render-utils/RenderUtils.h
Depends on #530 
Making a PR so that CI runs and, if it succeeds, so that someone can test it.
I don't have any Windows machines :/
=> Linux Port: Fix Windows Compilation (Untested)

alvr/client/android/app/src/main/cpp/ovr_context.cpp
=> Re-add color space and set to Rift S

alvr/dashboard/js/app/setupWizard.js
=> Do not support nonexistent gpu

alvr/common/src/data/session.rs, alvr/common/src/data/settings.rs, alvr/server/cpp/alvr_server/Settings.cpp, alvr/server/cpp/alvr_server/Settings.h, alvr/server/cpp/alvr_server/Statistics.h, alvr/server/src/connection.rs
Option to better utilize the network if fps drops
=> Add frametime for adaptive bitrate

alvr/client/android/app/src/main/cpp/ovr_context.cpp
Set independent of video resolution (2x eye/screen resolution)
=> Separate headset resolution

.github/stale.yml
close #792 
The merge requires the creation of a "stale" label.
=> Github: changed stale label

packaging/firewall/ufw-alvr
https://wiki.archlinux.org/title/Uncomplicated_Firewall#Adding_other_applications
=> Fix ufw app file

Cargo.lock, alvr/audio/Cargo.toml, alvr/audio/src/lib.rs, alvr/client/Cargo.toml, alvr/client/src/connection.rs, alvr/client/src/lib.rs, alvr/client/src/logging_backend.rs, alvr/commands/Cargo.toml, alvr/commands/src/lib.rs, alvr/common/Cargo.toml, alvr/common/src/lib.rs, alvr/experiments/client/Cargo.toml, alvr/experiments/gui/Cargo.toml, alvr/experiments/ipc/Cargo.toml, alvr/experiments/openvr_driver/Cargo.toml, alvr/launcher/Cargo.toml, alvr/server/Cargo.toml, alvr/server/src/connection.rs, alvr/server/src/dashboard.rs, alvr/server/src/lib.rs, alvr/server/src/logging_backend.rs, alvr/session/Cargo.toml, alvr/session/src/events.rs, alvr/settings-schema-derive/src/lib.rs, alvr/settings-schema/src/lib.rs, alvr/sockets/Cargo.toml, alvr/sockets/src/packets.rs, alvr/xtask/Cargo.toml, alvr/xtask/src/command.rs
Collect some dependencies in alvr_common
=> Switch from nalgebra to glam

.github/ISSUE_TEMPLATE/bug_report.md
This cleans up the bug reporting template.
=> Updated bug report template

packaging/alvr_build_linux.sh, packaging/alvr_build_linux_targets/debian.sh, packaging/alvr_build_linux_targets/fedora.sh, packaging/alvr_build_linux_targets/generic.sh, packaging/deb/control, packaging/rpm/alvr.spec
This will fix:
- Jack packaging support
This adds:
- Branch-specific build support
- Modular build script
- build artifact location unification
- Better nvidia dependency handling
=> Debian Package Fixes

alvr/server/cpp/alvr_server/PoseHistory.cpp
Matches the client
More info in discussions in the discord dev chat.
=> Change buffer size before popping

alvr/server/cpp/platform/win32/VideoEncoderSW.cpp
`pts` fields now use the refactored `targetTimestampNs`.
=> Change presentation time value with targetTimestampNs

alvr/server/cpp/alvr_server/OvrHMD.cpp
Sets the right boolean this time
=> fix linux async fix :P

packaging/alvr_build_linux_targets/generic.sh
Fixes debian builds and adds basic error handling for rustup installations.
=> Debian fixes

android/app/src/OculusQuest/AndroidManifest.xml
=> Add Handtracking 2.0 OwO

alvr/client/src/audio.rs
The server is buggy and sometimes chooses sample rates that are too low for audio use, which currently causes the client to crash. More specifically it chooses a bogus 1 Hz sample rate when using PulseAudio on Linux, which is the standard setup that almost all desktop Linux systems use - so I expect the client will pretty much always crash when trying to use audio with Linux on the server side unless the audio setup has been carefully reconfigured to work around this issue. This patch makes the client instead reject attempts to use such sample rates. (I'm planning on fixing the sample rate selection on the server too at some point but that's a little more complicated.)
Note that I can't fully test this due to not having a Quest - it works pretty much as expected on ALXR with the audio …
=> Client audio: don't crash if server sends invalid sample rate

alvr/server/src/connection.rs, alvr/session/src/settings.rs, dashboard/js/app/customSettings.js
- Removes the microphone output setting
- Removes the game audio device != microphone input requirement
=> Linux microphone settings tweaks

alvr/server/cpp/alvr_server/Settings.cpp, alvr/server/cpp/alvr_server/Settings.h, alvr/server/cpp/platform/linux/EncodePipeline.cpp, alvr/server/src/connection.rs, alvr/session/src/lib.rs, alvr/session/src/settings.rs
=> add force software encoding option

alvr/server/cpp/platform/linux/CEncoder.cpp, alvr/server/cpp/platform/linux/CEncoder.h
Should solve some possible launch crashes mentioned in the discord server.
=> [Linux] Switch to poll instead of select

packaging/alvr_build_linux.sh, packaging/alvr_build_linux_targets/debian.sh
Adds --no-nvidia flag
Fixes bug involving the control file
Updates build flags to --gpl in place of --bundle-ffmpeg
=> Update Linux build scripts

Cargo.lock, alvr/launcher/Cargo.toml, alvr/launcher/src/main.rs
Looks like the opengl backend of egui crashes on some nvidia configurations on linux, switching to wgpu seems to fix it.
=> Launcher fix

Cargo.lock, alvr/client_core/src/connection.rs, alvr/server/src/connection.rs, alvr/session/src/settings.rs, alvr/sockets/Cargo.toml, alvr/sockets/src/stream_socket/mod.rs, alvr/sockets/src/stream_socket/tcp.rs, alvr/sockets/src/stream_socket/throttled_udp.rs, alvr/sockets/src/stream_socket/udp.rs
4 new advanced settings are added to set the socket buffer size for client/server send/recv.
Need a rebase after merging previous PR.
=> Fix glitches on UDP 🎉

Cargo.lock, Cargo.toml, alvr/client_core/src/connection.rs, alvr/client_core/src/decoder.rs, alvr/client_core/src/lib.rs, alvr/client_core/src/platform/android.rs, alvr/client_core/src/platform/mod.rs, alvr/client_core/src/statistics.rs, alvr/events/src/lib.rs, alvr/server/src/statistics.rs, alvr/session/src/settings.rs, alvr/sockets/src/packets.rs, android/app/build.gradle, android/app/src/main/cpp/cpp_main.cpp, dashboard/js/app/monitor.js, dashboard/js/app/nls/monitor.js, packaging/deb/control, packaging/rpm/alvr.spec
Set video buffering in advanced settings, video tab, `maxBufferingFrames`. This reduces stutter frames.
=> Implement configurable video buffering

alvr/server/cpp/platform/win32/VideoEncoderVCE.cpp, dashboard/js/app/nls/settings.js
=> Fix 10-bit encoding with AMF

alvr/server/cpp/platform/linux/Renderer.cpp, alvr/server/cpp/platform/linux/ffmpeg_helper.cpp
Fixes aliasing on the edges with FFR.
=> Renderer: Enable anisotropic filtering

alvr/server/cpp/platform/linux/EncodePipelineVAAPI.cpp
=> VAAPI: Fix h264 with 10bit encoding enabled

alvr/dashboard/src/dashboard/components/connections.rs, alvr/dashboard/src/dashboard/components/installation.rs, alvr/dashboard/src/dashboard/components/logs.rs, alvr/dashboard/src/dashboard/components/settings_controls/text.rs, alvr/dashboard/src/dashboard/components/statistics.rs, alvr/dashboard/src/dashboard/mod.rs, alvr/dashboard/src/theme.rs
Styling improvements for the new dashboard, feedback is appreciated!
=> Styling improvements

alvr/server_data/src/lib.rs
Fixes periodic SessionUpdated spam.
=> Only call SessionUpdated when client IP actually changes

alvr/session/src/settings.rs, dashboard/js/app/nls/bg/settings.js, dashboard/js/app/nls/de/settings.js, dashboard/js/app/nls/es/settings.js, dashboard/js/app/nls/fr/settings.js, dashboard/js/app/nls/it/settings.js, dashboard/js/app/nls/ja/settings.js, dashboard/js/app/nls/ko/settings.js, dashboard/js/app/nls/ru/settings.js, dashboard/js/app/nls/settings.js, dashboard/js/app/nls/sl/settings.js, dashboard/js/app/nls/zh/settings.js
Remove unused realtime decoder option and set proper operation rate.
=> Remove unused decoder setting

alvr/server/cpp/platform/win32/CEncoder.cpp, alvr/server/cpp/platform/win32/VideoEncoderSW.cpp
=> Fix software encoding on Windows

alvr/server/cpp/platform/linux/EncodePipelineVAAPI.cpp
https://gitlab.freedesktop.org/mesa/mesa/-/commit/a727ec83ba01776e9c6f61c912c4caac280e968e
=> VAAPI: Enable VBAQ

alvr/vulkan_layer/layer/device_api.cpp, alvr/vulkan_layer/layer/private_data.hpp
=> vulkan_layer: Fix VK_KHR_display implementation

alvr/server_data/src/lib.rs
It's only used to detect GPU vendor/name, so only keep the AdapterInfo.
=> ServerDataManager: Don't keep wgpu::Instance around

wiki/Linux-encoders-requirements.md, wiki/_Sidebar.md
I can't confirm the nvenc test commands work, I just copied it from ffmpeg wiki.
=> Wiki: Linux encoders requirements

README.md
The links in the README were broken, so I fixed them. I think this is all of them
=> Fix wiki links

alvr/server/src/lib.rs, alvr/server/src/web_server.rs, alvr/server_data/src/lib.rs, dashboard/js/app/nls/wizard.js, dashboard/js/app/setupWizard.js
Changes the web API to return multiple adapters and displays them in setup wizard:
=> Return multiple GPUs and show them in setup wizard

alvr/server/cpp/platform/linux/EncodePipelineNvEnc.cpp
Also add support for rate control, quality, aq and weighted prediction.
=> Linux NVENC: Fix setting encoder options

alvr/server/src/lib.rs, alvr/server/src/web_server.rs, alvr/server_data/Cargo.toml, alvr/server_data/src/lib.rs, alvr/sockets/src/packets.rs, dashboard/js/app/setupWizard.js, dashboard/js/app/templates/wizard.html
Removes GPU detection and corresponding functions. Possibly fixes https://github.com/alvr-org/ALVR/issues/1303.
=> Remove GPU detection

alvr/sockets/src/stream_socket/tcp.rs, alvr/sockets/src/stream_socket/udp.rs
This reverts commit b827d1d489126fe14369fb6620259b12dd602532.
=> Revert "Set reuse address for TCP and UDP (#1323)"

alvr/server/cpp/alvr_server/ChaperoneUpdater.cpp, alvr/server/cpp/alvr_server/OvrHMD.h, alvr/server/cpp/alvr_server/PoseHistory.cpp, alvr/server/cpp/alvr_server/PoseHistory.h, alvr/server/cpp/alvr_server/alvr_server.cpp
=> Fix SteamVR recentering on Linux

alvr/client_opengl/cpp/ffr.cpp, alvr/client_opengl/cpp/graphics.cpp, alvr/client_opengl/cpp/staging_pass.cpp, alvr/client_opengl/cpp/staging_pass.h, alvr/client_openxr/src/lib.rs
StagingPass is now used to copy the hardwareBuffer into a GL_TEXTURE_2D when FFR is disabled.
=> fix re-projection by introducing StagingPass

alvr/server/cpp/platform/linux/EncodePipelineAMF.cpp
=> AMF: Wait on AMF surface semaphore

alvr/client_openxr/src/interaction.rs
apparently the pico needs these, too.
=> Pico: restore squeeze and trigger click actions

alvr/client_openxr/src/lib.rs
fixes Pico getting ANR'd after waking up
=> Mark android input events unhandled

patches/FFmpeg-remove-unused-encode-decode-exts-eb0455d.patch
Adding this commit as .patch: https://github.com/FFmpeg/FFmpeg/commit/eb0455d64690eed0068e5cb202f72ecdf899837c
=> fix ffmpeg build on linux

alvr/client_openxr/src/lib.rs
1. `render_stream` needs to be called on every xr frame, even if there's no decoded frame to display. `render_stream` handles the reprojection when `hardware_buffer` is null. 
2. also going back to `last_good_views` instead of swapchain_idx based hash maps, as these didn't work well, apparently
=> fix jitter on missing frame

alvr/server/cpp/alvr_server/OvrController.cpp
Fixes https://github.com/alvr-org/ALVR/issues/1437.
=> Bring back velocity reporting

alvr/vulkan_layer/layer/alvr_x86_64.json, alvr/vulkan_layer/layer/layer.cpp, alvr/vulkan_layer/layer/layer.h, alvr/vulkan_layer/src/lib.rs
Also remove VK_LAYER_EXPORT and reduce exported symbols.
=> vulkan_layer: Use negotiate function

alvr/common/src/average.rs, alvr/server/src/bitrate.rs, alvr/server/src/connection.rs, alvr/server/src/lib.rs, alvr/session/src/settings.rs
* Fix average bitrate calculation
* More accurate framerate estimation
* Trigger bitrate update on framerate change
* Implement workaround for decoder runaway latency
=> New bitrate rewrite

alvr/server/cpp/alvr_server/NalParsing.cpp, alvr/server/cpp/platform/linux/EncodePipelineAMF.cpp, alvr/server/cpp/platform/linux/EncodePipelineAMF.h, alvr/server/cpp/platform/linux/EncodePipelineNvEnc.cpp, alvr/server/cpp/platform/linux/EncodePipelineSW.cpp, alvr/server/cpp/platform/linux/EncodePipelineVAAPI.cpp, alvr/server/cpp/platform/linux/amf_helper.cpp
=> Fix build with clang

packaging/alvr_build_linux.sh, packaging/alvr_build_linux_targets/debian.sh, wiki/Installation-guide.md
Hello again!
This PR makes the Debian build script work with the new naming scheme.
=> Adapt Debian build script

alvr/server/cpp/alvr_server/Controller.cpp, alvr/server/cpp/alvr_server/Controller.h
Also add missing finger animations for emulation modes other than Quest 2/Rift S
=> Fix index finger pose on Valve Index emulation

alvr/server/cpp/platform/linux/EncodePipelineVAAPI.cpp
It now fails with FFmpeg 6: Filters must be initialized before linking.
=> EncodePipelineVAAPI: Fix creating buffer filter

Cargo.toml, alvr/client_core/src/connection.rs, alvr/client_core/src/decoder.rs, alvr/server/cpp/alvr_server/NalParsing.cpp, alvr/server/cpp/alvr_server/alvr_server.cpp, alvr/server/cpp/alvr_server/bindings.h, alvr/server/src/connection.rs, alvr/server/src/lib.rs, alvr/server/src/web_server.rs, alvr/session/src/settings.rs, alvr/sockets/src/packets.rs, packaging/deb/control, packaging/rpm/alvr.spec
This is a stub to support dynamically selected encoder.
=> Select codec type lazily

alvr/server/cpp/platform/linux/EncodePipelineAMF.cpp, alvr/server/cpp/platform/win32/VideoEncoderVCE.cpp
Draft because waiting for a response from @deiteris on required infomation
=> AMF: fix encoding params

alvr/server/cpp/alvr_server/NalParsing.cpp, alvr/server/cpp/alvr_server/bindings.h, alvr/server/cpp/platform/linux/CEncoder.cpp, alvr/server/cpp/platform/linux/EncodePipeline.cpp, alvr/server/cpp/platform/linux/EncodePipeline.h, alvr/server/cpp/platform/linux/EncodePipelineSW.cpp, alvr/server/cpp/platform/linux/EncodePipelineSW.h, alvr/server/cpp/platform/win32/VideoEncoderNVENC.cpp, alvr/server/cpp/platform/win32/VideoEncoderSW.cpp, alvr/server/cpp/platform/win32/VideoEncoderVCE.cpp
Used in software encoder where only h264 is available.
=> Allow encoders to override codec to use

alvr/client_openxr/src/interaction.rs, alvr/client_openxr/src/lib.rs
* Use more let-else expressions
* Use channels between rendering and tracking thread
=> Client refactoring

Cargo.lock, Cargo.toml, alvr/client_core/src/connection.rs, alvr/client_openxr/src/lib.rs, alvr/packets/src/lib.rs, alvr/server/src/connection.rs, alvr/session/src/settings.rs, packaging/deb/control, packaging/rpm/alvr.spec
Currently the client-side foveation doesn't seem to be working.
=> Send negotiated config as JSON, apply client-side foveation

alvr/session/src/settings.rs
To be reviewed as new commits come in all changes will be done when marked as not a draft PR, for a final review
=> Settings: Better Defaults

wiki/ALVR-in-distrobox.md, wiki/Installation-guide.md
I just updated installation guide to note about the guide, and included the guide into the this repository as part of the wiki.
Added nightlies mention as well
=> Distrobox linux guidance wiki changes

alvr/server/src/lib.rs
This is what apparently what SteamVR wants
Note: Needs heavy testing
Please if you use nightly try this and leave a comment on this PR once we get 5-10 I'll merge
=> Driver: Only Init Once

Cargo.lock, alvr/filesystem/build.rs, alvr/filesystem/src/lib.rs, alvr/server_io/Cargo.toml, alvr/server_io/src/firewall.rs, alvr/xtask/src/build.rs
Only fixes Appimage firewall not build directory builds
=> Linux: Fix Firewall

alvr/dashboard/src/dashboard/components/statistics.rs, alvr/dashboard/src/dashboard/mod.rs, alvr/dashboard/src/main.rs, alvr/events/src/lib.rs, alvr/server/src/bitrate.rs, alvr/server/src/connection.rs, alvr/server/src/lib.rs, alvr/server/src/statistics.rs, alvr/session/src/settings.rs
Refactor statistics code
Add HMD plugged status
=> Add bitrate graph

wiki/Flatpak.md, wiki/Installation-guide.md
Updated the build command to grant Flatpak Builder access to see the directory and updated the wiki.
=> Update Flatpak docs

.github/workflows/prepare-release.yml, wiki/Flatpak.md
Added a job to the release action to generate a flatpak bundle. Also updated the wiki to account for this. This could probably be adapted for the nightlies, but I haven't seen the actions file for that.
=> Add Flatpak job to generate bundle

alvr/server/cpp/platform/linux/Renderer.cpp
Latest mesa now allows to submit RGB surfaces directly to encoder without having to do the NV12 conversion with shader, but it only works with formats with DCC disabled.
Filter out DCC enabled modifiers when allocating the output image.
(This also fixes GPU hang with mesa git, but that's a mesa bug).
=> Renderer: Don't use DCC formats for output image on Linux AMD

wiki/Flatpak.md
Remove mention of *some* release and point to nightly with flatpak bundle
Fix command for building & installing flatpak alvr
=> Flatpak wiki fixes

alvr/server/src/statistics.rs
This reverts commit 8867dd28c66f1cb9d15c0c61cdbb82f3e75efe33.
Closes https://github.com/alvr-org/ALVR/issues/1755
=> Revert "Fix controller tracking prediction logic"

alvr/vrcompositor_wrapper/drm-lease-shim.cpp
and pused real GPU back
Archlinux enabled SimpleFB kernel module which can create `/dev/dri/card0` early on during boot process, so let's just try next device. 
https://bbs.archlinux.org/viewtopic.php?id=288578
=> Linux: Try opening next dri device in case first is SimpleFB 

alvr/client_openxr/src/interaction.rs, alvr/client_openxr/src/lib.rs, alvr/session/src/settings.rs
=> feat(client_openxr): :recycle: Refactor code to support session reinitialization

alvr/client_openxr/Cargo.toml, alvr/client_openxr/src/interaction.rs, alvr/client_openxr/src/lib.rs, alvr/server/src/face_tracking.rs
This should be merged after #1900
=> feat: ✨ Support combined eye gaze

alvr/server/src/connection.rs, alvr/server/src/input_mapping.rs, alvr/server/src/openvr_props.rs, alvr/session/src/settings.rs
Add a Quest 3 Touch Plus controller emulation mode.
Change SteamVR Icons based on selected emulation mode
=> Added Touch Plus + Change Icon string based on emuation mode

Cargo.lock, alvr/xtask/src/dependencies.rs
=> update cargo.lock & oculus loader

alvr/server/cpp/platform/linux/EncodePipelineVAAPI.cpp
credit goes to @nowrep
tested, no issues for 6+ hours of use
=> fix(encoder): VAAPI h264 smearing

.github/workflows/prepare-release.yml
This should prevent android builds from failing in the future.
=> ci: making sure android builds don't fail

Cargo.lock, alvr/server/Cargo.toml, alvr/sockets/Cargo.toml, alvr/xtask/src/build.rs, alvr/xtask/src/main.rs, alvr/xtask/src/packaging.rs
Add profiling using tracy because tracy allows gpu profiling which is going to be super useful in the future
=> Feature: Add Profiling

alvr/client_core/cpp/graphics.cpp
(Subjectively) improves the appearance of the lobby scene.
- Makes the environment darker overall
- Makes the grid lines blue
- Makes the grid lines fade out over distance
- Tidied up some of the lobby fragment shader, commenting more lines
=> Make the lobby scene dark and add a bit of colour

alvr/server/cpp/platform/linux/CEncoder.cpp, alvr/server/cpp/platform/linux/EncodePipelineVAAPI.cpp, alvr/server/cpp/platform/linux/FrameRender.cpp, alvr/server/cpp/platform/linux/Renderer.cpp, alvr/server/cpp/platform/linux/Renderer.h
Also fix capture frame and allow to run without calibrated timestamps.
=> Linux: Fix VAAPI encoder on Intel GPUs

alvr/xtask/src/dependencies.rs
=> enable av1 ffmpeg nvenc

wiki/ALVR-in-distrobox.md, wiki/Installation-guide.md
Got a little bit outdated and i've changed how to switch to nightly.
Also reformatted a bit.
=> Updated installation notes and distrobox guide wiki.

wiki/Hardware-Video-Encoding.md, wiki/_Sidebar.md
- Add testing documentation for FFmpeg hardware encoding
- Include background information about components
=> Add Documentation for Hardware Encoding Testing

wiki/Flatpak.md
Oops forgot to update it with flatpak fixes
=> docs(flatpak): 📝 Fix flatpak package sdk/runtime versions

alvr/client_core/cpp/graphics.cpp
- crashes when restarting alvr_client activity
=> fix: fix warmstart crashes and memory leaks in client_core gfx

alvr/server/src/sockets.rs, alvr/sockets/src/lib.rs
Also, improve error message for mismatched version.
=> fix(server): :bug: Use device_id field for hostname instead of mDNS hostname

wiki/Use-ALVR-through-a-USB-connection.md
Noticed it's not correct (wifi is not required anymore) and made some text bald to make sure people don't miss it
Also added note for dev account, usb debug on headsets
=> Updated wired mode wiki page

CHANGELOG.md, Cargo.lock, alvr/audio/Cargo.toml, alvr/audio/src/windows.rs, alvr/client_core/Cargo.toml, alvr/client_core/src/decoder.rs, alvr/client_core/src/platform/android/decoder.rs, alvr/client_openxr/Cargo.toml, alvr/common/Cargo.toml, alvr/common/src/logging.rs, alvr/dashboard/Cargo.toml, alvr/launcher/Cargo.toml, alvr/server/Cargo.toml
Note: it includes some non trivial changes but they have been tested
Tested on Windows + Quest 1
=> zarik-staging

Cargo.lock, Cargo.toml, alvr/client_core/src/connection.rs, alvr/client_core/src/platform/android/mod.rs, alvr/client_core/src/sockets.rs, alvr/client_core/src/storage.rs, alvr/client_openxr/Cargo.toml, alvr/server/src/sockets.rs
This is part 1 of a sockets rewrite v3.
Once this PR is merged, the branch will be reused.
NB: This is the first commit in a while that bumps the protocol (-devXX)
=> feat: :sparkles: Add mDNS support to Android; remove broadcast

alvr/session/src/settings.rs
Also disallow collapsing for some sections
=> feat(session): :sparkles: Reorder settings to be easier to use

.github/workflows/rust.yml, Cargo.lock, alvr/server/cpp/alvr_server/Utils.h, alvr/server/cpp/alvr_server/alvr_server.cpp, alvr/server/cpp/platform/linux/FrameRender.cpp, alvr/server/cpp/platform/win32/VideoEncoderSW.h, alvr/xtask/Cargo.toml, alvr/xtask/src/format.rs, alvr/xtask/src/main.rs
The CI failure for rustfmt is expected as all the big changes aren't in tree yet, so it should be failing.
=> chore: add c++ autoformatter

alvr/client_core/src/connection.rs
=> fix(client_core): :bug: Fix USB mode

alvr/client_core/resources/lobby_fragment.glsl
I planned to commit more stuff later but probably this will be the last commit from me for v20.9.0.
=> zarik staging

wiki/Linux-Troubleshooting.md
Small changes, seemed to be relevant recently
=> docs: light refactor of linux troubleshooting page, add wlroots compositor mention

wiki/ALVR-Checklist.md, wiki/ALVR-wired-setup-(ALVR-over-USB).md, wiki/Controller-latency.md, wiki/FFmpeg-Hardware-Encoding-Testing.md, wiki/Fixed-Foveated-Rendering-(FFR).md, wiki/Headset-and-ALVR-streamer-on-separate-networks.md, wiki/How-ALVR-works.md, wiki/Information-and-Recommendations.md, wiki/Installation-guide.md, wiki/Installing-ALVR-and-using-SteamVR-on-Linux-through-Flatpak.md, wiki/Linux-Troubleshooting.md, wiki/Real-time-video-upscaling-experiments.md, wiki/Roadmap.md, wiki/Settings-tutorial.md, wiki/Troubleshooting.md
=> docs: Put page title into file name

alvr/xtask/src/dependencies.rs
Missed this among the Focus 3 fixes
=> fix(xtask): :bug: Downgrade loader

Cargo.lock, alvr/client_core/Cargo.toml, alvr/client_core/src/graphics/lobby.rs, alvr/client_core/src/graphics/mod.rs, alvr/dashboard/Cargo.toml
This reverts commit 4f7aa2e19698abbe0105d58e6cec4fec264dc107.
=> Revert "build: :arrow_up: Update dependencies"

alvr/dashboard/src/dashboard/components/settings_controls/presets/builtin_schema.rs, alvr/server_core/src/connection.rs, alvr/server_openvr/cpp/alvr_server/Controller.cpp, alvr/server_openvr/cpp/alvr_server/Controller.h, alvr/server_openvr/cpp/alvr_server/Settings.cpp, alvr/server_openvr/cpp/alvr_server/Settings.h, alvr/server_openvr/cpp/alvr_server/alvr_server.cpp, alvr/session/src/lib.rs, alvr/session/src/settings.rs
=> fix(server): :bug: Fix controllers tracking on VRChat

alvr/server_openvr/cpp/alvr_server/alvr_server.cpp
=> fix(server_openvr): :bug: Fix crash when disabling separate hand trackers

wiki/Installation-guide.md
Fixed a minor broken link in the wiki.
=> wiki: Fix link

alvr/server_openvr/src/tracking.rs
We need to discuss if this change should be merged
=> fix(server_openvr): :bug: Set body trackers as disabled if not tracking

alvr/client_openxr/src/lib.rs, alvr/xtask/src/dependencies.rs
Tested on Pico 4 Ultra. I need this for work
=> feat: :sparkles: Use generic loader for Pico >= 4

alvr/server_openvr/cpp/alvr_server/Controller.cpp, alvr/server_openvr/cpp/alvr_server/Controller.h, alvr/server_openvr/cpp/alvr_server/FakeViveTracker.cpp, alvr/server_openvr/cpp/alvr_server/FakeViveTracker.h, alvr/server_openvr/cpp/alvr_server/HMD.cpp, alvr/server_openvr/cpp/alvr_server/HMD.h, alvr/server_openvr/cpp/alvr_server/Paths.cpp, alvr/server_openvr/cpp/alvr_server/Paths.h, alvr/server_openvr/cpp/alvr_server/TrackedDevice.cpp, alvr/server_openvr/cpp/alvr_server/TrackedDevice.h, alvr/server_openvr/cpp/alvr_server/ViveTrackerProxy.cpp, alvr/server_openvr/cpp/alvr_server/alvr_server.cpp, alvr/server_openvr/cpp/alvr_server/bindings.h, alvr/server_openvr/src/lib.rs, alvr/server_openvr/src/props.rs, alvr/server_openvr/src/tracking.rs
This PR pulls the first two commits from the branch zarik_staging. After 2 days I will merge it, if not reviewed before.
=> Zmerp staging

alvr/client_core/src/platform/mod.rs
I've checked that I'm not breaking other code doing platform matching.
=> fix(client_core): :bug: Fix Pico 4 detection; add Focus Vision

alvr/common/src/connection_result.rs
=> fix(sockets): :bug: Ignore error 997 (overlapped IO)

.github/workflows/prepare-release.yml, alvr/common/Cargo.toml, alvr/common/src/logging.rs, alvr/xtask/src/build.rs, alvr/xtask/src/dependencies.rs, alvr/xtask/src/main.rs, alvr/xtask/src/packaging.rs
This includes also the removal of appimage build code and removal of enable-messagebox feature.
=> fix(xtask): 🐛 Fix package commands; update release ci

.github/workflows/rust.yml, Cargo.lock, alvr/xtask/Cargo.toml, alvr/xtask/src/ci.rs, alvr/xtask/src/main.rs
~~Note: Supposed to be a draft pr, but I need the CI to run, so...~~
=> chore(ci): update deprecated actions

alvr/client_openxr/src/interaction.rs, alvr/client_openxr/src/stream.rs
I need this for a private fork for work
=> refactor(client_openxr): :recycle: Refactor around reference spaces

Cargo.lock, alvr/client_core/src/connection.rs, alvr/client_core/src/lib.rs, alvr/client_openxr/src/interaction.rs, alvr/client_openxr/src/stream.rs, alvr/session/src/settings.rs
This *might* fix the prediction failure reported by JXI
=> fix(client_openxr): :bug: Fix head angular velocity

alvr/server_core/src/tracking/mod.rs
Tested by rubjonny on Discord.
Closes #2498
Closes #2584
=> fix(server_core): :bug: Fix controllers disabling with lag

alvr/client_core/resources/lobby_line.wgsl, alvr/client_core/src/c_api.rs, alvr/client_core/src/graphics/lobby.rs, alvr/client_core/src/graphics/mod.rs, alvr/client_core/src/graphics/stream.rs, alvr/client_openxr/src/interaction.rs, alvr/client_openxr/src/lib.rs, alvr/client_openxr/src/lobby.rs, alvr/client_openxr/src/stream.rs
Tested on: Quest 3, Vive Focus 3, Pico Neo 3, Pico 4 Ultra
=> fix(client): :bug: Fix controller angular velocity for some devices; show velocities in lobby

alvr/server_core/src/connection.rs, alvr/xtask/src/ci.rs
From #2625 but with standalone branch
=> refactor(server_core): 🚨 Fix lints and fail CI on clippy warnings

Cargo.lock, alvr/dashboard/Cargo.toml, alvr/dashboard/src/main.rs, alvr/dashboard/src/steamvr_launcher/linux_steamvr.rs, alvr/graphics/Cargo.toml, alvr/graphics/src/lib.rs, alvr/graphics/src/lobby.rs, alvr/graphics/src/stream.rs
No problems with this PR. After this is merged I will update egui
=> refactor: :arrow_up: Update wgpu

wiki/Installation-guide.md
=> Update Microphone Setup on Windows (installation-guide.md)

alvr/xtask/flatpak/com.valvesoftware.Steam.Utility.alvr.json
Trying to fix nightly breakage
=> build(xtask): :bug: Update LLVM in Flatpak

alvr/dashboard/src/dashboard/components/settings_controls/mod.rs
This fixes the foveation preset which uses whole number floats
=> fix(dashboard): :bug: Fix floats read as integer in json equality

alvr/gui_common/src/theme.rs
This PR forces the theme to Dark instead of System
Closes #2760
Supersedes #2761
=> fix(dashboard): :bug: Fix theme when system is set to light

alvr/client_openxr/src/extra_extensions/face_tracking_pico.rs, alvr/client_openxr/src/interaction.rs, alvr/server_core/src/tracking/face.rs
Supersedes https://github.com/alvr-org/ALVR/pull/2738.
=> refactor: Remove Pico audio visemes

alvr/dashboard/src/dashboard/components/new_version_popup.rs, alvr/dashboard/src/dashboard/mod.rs, alvr/dashboard/src/data_sources.rs, alvr/session/src/settings.rs
The last refactor before merging broke a couple of things, plus I changed to a different settings format
Tested and working using stable and -dev versions
=> fix(dashboard): :bug: Fix version popup

alvr/audio/src/lib.rs
=> fix(audio): :bug: Fix yet another string missed before

Cargo.lock, alvr/audio/Cargo.toml, alvr/audio/src/lib.rs, alvr/audio/src/windows.rs, alvr/client_core/src/audio.rs, alvr/client_core/src/connection.rs, alvr/server_core/src/connection.rs, alvr/server_io/Cargo.toml
- fix cpal device enumeration being extremely slow on v0.15
- make device comparison compare ids
- actually respect virtual audio cable search ordering
=> fix: bump cpal+rodio, fix os error 11 timeout

alvr/dashboard/src/main.rs
=> fix: dashboard suiciding due to ignoring symlinks

alvr/dashboard/src/dashboard/components/debug.rs, alvr/dashboard/src/dashboard/components/devices.rs, alvr/dashboard/src/dashboard/components/installation.rs, alvr/dashboard/src/dashboard/components/new_version_popup.rs, alvr/dashboard/src/dashboard/components/settings.rs, alvr/dashboard/src/dashboard/components/setup_wizard.rs, alvr/dashboard/src/dashboard/mod.rs, alvr/dashboard/src/data_sources.rs, alvr/packets/src/lib.rs, alvr/server_core/src/connection.rs, alvr/server_core/src/lib.rs, alvr/server_core/src/web_server.rs, alvr/server_io/src/lib.rs
Spit `/api/dashboard-request` into separate requests, using GET and POST appropriately.
Also do some renaming and refactoring
=> feat(server): ✨ Split dashboard-request
